// Code generated by protoc-gen-go.
// source: bfgateway.proto
// DO NOT EDIT!

/*
Package bfgateway is a generated protocol buffer package.

It is generated from these files:
	bfgateway.proto

It has these top-level messages:
	BfVoid
	BfTickData
	BfTradeData
	BfOrderData
	BfPositionData
	BfAccountData
	BfErrorData
	BfLogData
	BfContractData
	BfNotificationData
	BfPingData
	BfKvData
	BfSendOrderReq
	BfSendOrderResp
	BfCancelOrderReq
	BfConnectReq
	BfGetContractReq
*/
package bfgateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 方向常量
type BfDirection int32

const (
	BfDirection_DIRECTION_UNKNOWN BfDirection = 0
	BfDirection_DIRECTION_LONG    BfDirection = 1
	BfDirection_DIRECTION_SHORT   BfDirection = 2
	BfDirection_DIRECTION_NET     BfDirection = 3
)

var BfDirection_name = map[int32]string{
	0: "DIRECTION_UNKNOWN",
	1: "DIRECTION_LONG",
	2: "DIRECTION_SHORT",
	3: "DIRECTION_NET",
}
var BfDirection_value = map[string]int32{
	"DIRECTION_UNKNOWN": 0,
	"DIRECTION_LONG":    1,
	"DIRECTION_SHORT":   2,
	"DIRECTION_NET":     3,
}

func (x BfDirection) String() string {
	return proto.EnumName(BfDirection_name, int32(x))
}
func (BfDirection) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 开平常量
type BfOffset int32

const (
	BfOffset_OFFSET_UNKNOWN        BfOffset = 0
	BfOffset_OFFSET_OPEN           BfOffset = 1
	BfOffset_OFFSET_CLOSE          BfOffset = 2
	BfOffset_OFFSET_CLOSETODAY     BfOffset = 3
	BfOffset_OFFSET_CLOSEYESTERDAY BfOffset = 4
)

var BfOffset_name = map[int32]string{
	0: "OFFSET_UNKNOWN",
	1: "OFFSET_OPEN",
	2: "OFFSET_CLOSE",
	3: "OFFSET_CLOSETODAY",
	4: "OFFSET_CLOSEYESTERDAY",
}
var BfOffset_value = map[string]int32{
	"OFFSET_UNKNOWN":        0,
	"OFFSET_OPEN":           1,
	"OFFSET_CLOSE":          2,
	"OFFSET_CLOSETODAY":     3,
	"OFFSET_CLOSEYESTERDAY": 4,
}

func (x BfOffset) String() string {
	return proto.EnumName(BfOffset_name, int32(x))
}
func (BfOffset) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 状态常量
type BfStatus int32

const (
	BfStatus_STATUS_UNKNOWN    BfStatus = 0
	BfStatus_STATUS_NOTTRADED  BfStatus = 1
	BfStatus_STATUS_PARTTRADED BfStatus = 2
	BfStatus_STATUS_ALLTRADED  BfStatus = 3
	BfStatus_STATUS_CANCELLED  BfStatus = 4
)

var BfStatus_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "STATUS_NOTTRADED",
	2: "STATUS_PARTTRADED",
	3: "STATUS_ALLTRADED",
	4: "STATUS_CANCELLED",
}
var BfStatus_value = map[string]int32{
	"STATUS_UNKNOWN":    0,
	"STATUS_NOTTRADED":  1,
	"STATUS_PARTTRADED": 2,
	"STATUS_ALLTRADED":  3,
	"STATUS_CANCELLED":  4,
}

func (x BfStatus) String() string {
	return proto.EnumName(BfStatus_name, int32(x))
}
func (BfStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 合约类型常量
type BfProduct int32

const (
	BfProduct_PRODUCT_UNKNOWN BfProduct = 0
	BfProduct_PRODUCT_EQUITY  BfProduct = 1
	BfProduct_PRODUCT_FUTURES BfProduct = 2
)

var BfProduct_name = map[int32]string{
	0: "PRODUCT_UNKNOWN",
	1: "PRODUCT_EQUITY",
	2: "PRODUCT_FUTURES",
}
var BfProduct_value = map[string]int32{
	"PRODUCT_UNKNOWN": 0,
	"PRODUCT_EQUITY":  1,
	"PRODUCT_FUTURES": 2,
}

func (x BfProduct) String() string {
	return proto.EnumName(BfProduct_name, int32(x))
}
func (BfProduct) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 价格类型常量
type BfPriceType int32

const (
	BfPriceType_PRICETYPE_UNKONWN     BfPriceType = 0
	BfPriceType_PRICETYPE_LIMITPRICE  BfPriceType = 1
	BfPriceType_PRICETYPE_MARKETPRICE BfPriceType = 2
)

var BfPriceType_name = map[int32]string{
	0: "PRICETYPE_UNKONWN",
	1: "PRICETYPE_LIMITPRICE",
	2: "PRICETYPE_MARKETPRICE",
}
var BfPriceType_value = map[string]int32{
	"PRICETYPE_UNKONWN":     0,
	"PRICETYPE_LIMITPRICE":  1,
	"PRICETYPE_MARKETPRICE": 2,
}

func (x BfPriceType) String() string {
	return proto.EnumName(BfPriceType_name, int32(x))
}
func (BfPriceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// Notification
type BfNoticationType int32

const (
	BfNoticationType_NOTIFICATION_UNKNOWN        BfNoticationType = 0
	BfNoticationType_NOTIFICATION_TRADEWILLBEGIN BfNoticationType = 1
	BfNoticationType_NOTIFICATION_GOTCONTRACTS   BfNoticationType = 2
)

var BfNoticationType_name = map[int32]string{
	0: "NOTIFICATION_UNKNOWN",
	1: "NOTIFICATION_TRADEWILLBEGIN",
	2: "NOTIFICATION_GOTCONTRACTS",
}
var BfNoticationType_value = map[string]int32{
	"NOTIFICATION_UNKNOWN":        0,
	"NOTIFICATION_TRADEWILLBEGIN": 1,
	"NOTIFICATION_GOTCONTRACTS":   2,
}

func (x BfNoticationType) String() string {
	return proto.EnumName(BfNoticationType_name, int32(x))
}
func (BfNoticationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// 空参数
type BfVoid struct {
}

func (m *BfVoid) Reset()                    { *m = BfVoid{} }
func (m *BfVoid) String() string            { return proto.CompactTextString(m) }
func (*BfVoid) ProtoMessage()               {}
func (*BfVoid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Tick行情数据类
type BfTickData struct {
	// 代码相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 成交数据
	ActionDate   string  `protobuf:"bytes,3,opt,name=actionDate" json:"actionDate,omitempty"`
	TickTime     string  `protobuf:"bytes,4,opt,name=tickTime" json:"tickTime,omitempty"`
	LastPrice    float64 `protobuf:"fixed64,5,opt,name=lastPrice" json:"lastPrice,omitempty"`
	Volume       int32   `protobuf:"varint,6,opt,name=volume" json:"volume,omitempty"`
	OpenInterest float64 `protobuf:"fixed64,7,opt,name=openInterest" json:"openInterest,omitempty"`
	LastVolume   int32   `protobuf:"varint,8,opt,name=lastVolume" json:"lastVolume,omitempty"`
	// 常规行情
	OpenPrice     float64 `protobuf:"fixed64,9,opt,name=openPrice" json:"openPrice,omitempty"`
	HighPrice     float64 `protobuf:"fixed64,10,opt,name=highPrice" json:"highPrice,omitempty"`
	LowPrice      float64 `protobuf:"fixed64,11,opt,name=lowPrice" json:"lowPrice,omitempty"`
	PreClosePrice float64 `protobuf:"fixed64,12,opt,name=preClosePrice" json:"preClosePrice,omitempty"`
	UpperLimit    float64 `protobuf:"fixed64,13,opt,name=upperLimit" json:"upperLimit,omitempty"`
	LowerLimit    float64 `protobuf:"fixed64,14,opt,name=lowerLimit" json:"lowerLimit,omitempty"`
	// x档行情
	BidPrice1  float64 `protobuf:"fixed64,15,opt,name=bidPrice1" json:"bidPrice1,omitempty"`
	AskPrice1  float64 `protobuf:"fixed64,16,opt,name=askPrice1" json:"askPrice1,omitempty"`
	BidVolume1 int32   `protobuf:"varint,17,opt,name=bidVolume1" json:"bidVolume1,omitempty"`
	AskVolume1 int32   `protobuf:"varint,18,opt,name=askVolume1" json:"askVolume1,omitempty"`
}

func (m *BfTickData) Reset()                    { *m = BfTickData{} }
func (m *BfTickData) String() string            { return proto.CompactTextString(m) }
func (*BfTickData) ProtoMessage()               {}
func (*BfTickData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 成交数据类
type BfTradeData struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	TradeId  string `protobuf:"bytes,3,opt,name=tradeId" json:"tradeId,omitempty"`
	// 对于ctp/lts是frontid.sessioni.orderref
	// ctp/lts的trade里面没有frontid+sessionid
	// 内部通过sysOrderId是做了映射trade到Order
	BfOrderId string `protobuf:"bytes,4,opt,name=bfOrderId" json:"bfOrderId,omitempty"`
	// 成交相关
	Direction BfDirection `protobuf:"varint,5,opt,name=direction,enum=bfgateway.BfDirection" json:"direction,omitempty"`
	Offset    BfOffset    `protobuf:"varint,6,opt,name=offset,enum=bfgateway.BfOffset" json:"offset,omitempty"`
	Price     float64     `protobuf:"fixed64,7,opt,name=price" json:"price,omitempty"`
	Volume    int32       `protobuf:"varint,8,opt,name=volume" json:"volume,omitempty"`
	TradeDate string      `protobuf:"bytes,9,opt,name=tradeDate" json:"tradeDate,omitempty"`
	TradeTime string      `protobuf:"bytes,10,opt,name=tradeTime" json:"tradeTime,omitempty"`
}

func (m *BfTradeData) Reset()                    { *m = BfTradeData{} }
func (m *BfTradeData) String() string            { return proto.CompactTextString(m) }
func (*BfTradeData) ProtoMessage()               {}
func (*BfTradeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 订单数据类
type BfOrderData struct {
	// 代码编号相关
	Symbol    string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange  string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	BfOrderId string `protobuf:"bytes,3,opt,name=bfOrderId" json:"bfOrderId,omitempty"`
	// 报单相关
	Direction    BfDirection `protobuf:"varint,4,opt,name=direction,enum=bfgateway.BfDirection" json:"direction,omitempty"`
	Offset       BfOffset    `protobuf:"varint,5,opt,name=offset,enum=bfgateway.BfOffset" json:"offset,omitempty"`
	Price        float64     `protobuf:"fixed64,6,opt,name=price" json:"price,omitempty"`
	TotalVolume  int32       `protobuf:"varint,7,opt,name=totalVolume" json:"totalVolume,omitempty"`
	TradedVolume int32       `protobuf:"varint,8,opt,name=tradedVolume" json:"tradedVolume,omitempty"`
	Status       BfStatus    `protobuf:"varint,9,opt,name=status,enum=bfgateway.BfStatus" json:"status,omitempty"`
	InsertDate   string      `protobuf:"bytes,10,opt,name=insertDate" json:"insertDate,omitempty"`
	InsertTime   string      `protobuf:"bytes,11,opt,name=insertTime" json:"insertTime,omitempty"`
	CancelTime   string      `protobuf:"bytes,12,opt,name=cancelTime" json:"cancelTime,omitempty"`
}

func (m *BfOrderData) Reset()                    { *m = BfOrderData{} }
func (m *BfOrderData) String() string            { return proto.CompactTextString(m) }
func (*BfOrderData) ProtoMessage()               {}
func (*BfOrderData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 持仓数据类
type BfPositionData struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 持仓相关
	Direction  BfDirection `protobuf:"varint,3,opt,name=direction,enum=bfgateway.BfDirection" json:"direction,omitempty"`
	Position   int32       `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
	Frozen     int32       `protobuf:"varint,5,opt,name=frozen" json:"frozen,omitempty"`
	Price      float64     `protobuf:"fixed64,6,opt,name=price" json:"price,omitempty"`
	YdPosition int32       `protobuf:"varint,7,opt,name=ydPosition" json:"ydPosition,omitempty"`
}

func (m *BfPositionData) Reset()                    { *m = BfPositionData{} }
func (m *BfPositionData) String() string            { return proto.CompactTextString(m) }
func (*BfPositionData) ProtoMessage()               {}
func (*BfPositionData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 账户数据类
type BfAccountData struct {
	// 账号代码相关
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	// 数值相关
	PreBalance     float64 `protobuf:"fixed64,2,opt,name=preBalance" json:"preBalance,omitempty"`
	Balance        float64 `protobuf:"fixed64,3,opt,name=balance" json:"balance,omitempty"`
	Available      float64 `protobuf:"fixed64,4,opt,name=available" json:"available,omitempty"`
	Commission     float64 `protobuf:"fixed64,5,opt,name=commission" json:"commission,omitempty"`
	FrozenMargin   float64 `protobuf:"fixed64,6,opt,name=frozenMargin" json:"frozenMargin,omitempty"`
	CloseProfit    float64 `protobuf:"fixed64,7,opt,name=closeProfit" json:"closeProfit,omitempty"`
	PositionProfit float64 `protobuf:"fixed64,8,opt,name=positionProfit" json:"positionProfit,omitempty"`
}

func (m *BfAccountData) Reset()                    { *m = BfAccountData{} }
func (m *BfAccountData) String() string            { return proto.CompactTextString(m) }
func (*BfAccountData) ProtoMessage()               {}
func (*BfAccountData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// 错误数据类
type BfErrorData struct {
	Code      int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	MessageEx string `protobuf:"bytes,3,opt,name=messageEx" json:"messageEx,omitempty"`
}

func (m *BfErrorData) Reset()                    { *m = BfErrorData{} }
func (m *BfErrorData) String() string            { return proto.CompactTextString(m) }
func (*BfErrorData) ProtoMessage()               {}
func (*BfErrorData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 日志数据类
type BfLogData struct {
	When    string `protobuf:"bytes,1,opt,name=when" json:"when,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *BfLogData) Reset()                    { *m = BfLogData{} }
func (m *BfLogData) String() string            { return proto.CompactTextString(m) }
func (*BfLogData) ProtoMessage()               {}
func (*BfLogData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// 合约详细信息类
type BfContractData struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// TODO(hege):utf8
	Name           string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ProductClass   BfProduct `protobuf:"varint,4,opt,name=productClass,enum=bfgateway.BfProduct" json:"productClass,omitempty"`
	VolumeMultiple int32     `protobuf:"varint,5,opt,name=volumeMultiple" json:"volumeMultiple,omitempty"`
	PriceTick      float64   `protobuf:"fixed64,6,opt,name=priceTick" json:"priceTick,omitempty"`
	MaxLimit       int32     `protobuf:"varint,7,opt,name=maxLimit" json:"maxLimit,omitempty"`
	MinLimit       int32     `protobuf:"varint,8,opt,name=minLimit" json:"minLimit,omitempty"`
	MaxMarket      int32     `protobuf:"varint,9,opt,name=maxMarket" json:"maxMarket,omitempty"`
	MinMarket      int32     `protobuf:"varint,10,opt,name=minMarket" json:"minMarket,omitempty"`
}

func (m *BfContractData) Reset()                    { *m = BfContractData{} }
func (m *BfContractData) String() string            { return proto.CompactTextString(m) }
func (*BfContractData) ProtoMessage()               {}
func (*BfContractData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// Notification
type BfNotificationData struct {
	Type      BfNoticationType `protobuf:"varint,1,opt,name=type,enum=bfgateway.BfNoticationType" json:"type,omitempty"`
	Code      int32            `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Message   string           `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	MessageEx string           `protobuf:"bytes,4,opt,name=messageEx" json:"messageEx,omitempty"`
}

func (m *BfNotificationData) Reset()                    { *m = BfNotificationData{} }
func (m *BfNotificationData) String() string            { return proto.CompactTextString(m) }
func (*BfNotificationData) ProtoMessage()               {}
func (*BfNotificationData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// Ping/Pong检测传入的对象类
// 同ctp一样，5秒一次
type BfPingData struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *BfPingData) Reset()                    { *m = BfPingData{} }
func (m *BfPingData) String() string            { return proto.CompactTextString(m) }
func (*BfPingData) ProtoMessage()               {}
func (*BfPingData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// K/V数据交换传入传出的数据类
// 策略间交换数据服务
// 由于涉及交易，交易又分实盘和回测，所以放到网关比较合适
type BfKvData struct {
	// kv对
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *BfKvData) Reset()                    { *m = BfKvData{} }
func (m *BfKvData) String() string            { return proto.CompactTextString(m) }
func (*BfKvData) ProtoMessage()               {}
func (*BfKvData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

// 发单时传入的对象类
type BfSendOrderReq struct {
	// 代码编号相关
	Symbol    string      `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange  string      `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	Price     float64     `protobuf:"fixed64,3,opt,name=price" json:"price,omitempty"`
	Volume    int32       `protobuf:"varint,4,opt,name=volume" json:"volume,omitempty"`
	PriceType BfPriceType `protobuf:"varint,5,opt,name=priceType,enum=bfgateway.BfPriceType" json:"priceType,omitempty"`
	Direction BfDirection `protobuf:"varint,6,opt,name=direction,enum=bfgateway.BfDirection" json:"direction,omitempty"`
	Offset    BfOffset    `protobuf:"varint,7,opt,name=offset,enum=bfgateway.BfOffset" json:"offset,omitempty"`
}

func (m *BfSendOrderReq) Reset()                    { *m = BfSendOrderReq{} }
func (m *BfSendOrderReq) String() string            { return proto.CompactTextString(m) }
func (*BfSendOrderReq) ProtoMessage()               {}
func (*BfSendOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// 发单本地返回的对象类
type BfSendOrderResp struct {
	BfOrderId string `protobuf:"bytes,1,opt,name=bfOrderId" json:"bfOrderId,omitempty"`
}

func (m *BfSendOrderResp) Reset()                    { *m = BfSendOrderResp{} }
func (m *BfSendOrderResp) String() string            { return proto.CompactTextString(m) }
func (*BfSendOrderResp) ProtoMessage()               {}
func (*BfSendOrderResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// 撤单时传入的对象类
type BfCancelOrderReq struct {
	// 代码编号相关
	Symbol    string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange  string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	BfOrderId string `protobuf:"bytes,3,opt,name=bfOrderId" json:"bfOrderId,omitempty"`
}

func (m *BfCancelOrderReq) Reset()                    { *m = BfCancelOrderReq{} }
func (m *BfCancelOrderReq) String() string            { return proto.CompactTextString(m) }
func (*BfCancelOrderReq) ProtoMessage()               {}
func (*BfCancelOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// 连接时传入的对象类
type BfConnectReq struct {
	// 代号
	ClientId string `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty"`
	// 可扩展参数
	IntParam int32  `protobuf:"varint,2,opt,name=intParam" json:"intParam,omitempty"`
	StrParam string `protobuf:"bytes,3,opt,name=strParam" json:"strParam,omitempty"`
	// 角色类别，可多选
	// 注意：OnTradeWillBegin OnGotContracts OnPing 都必须实现
	TickHandler  bool `protobuf:"varint,4,opt,name=tickHandler" json:"tickHandler,omitempty"`
	TradeHandler bool `protobuf:"varint,5,opt,name=tradeHandler" json:"tradeHandler,omitempty"`
	LogHandler   bool `protobuf:"varint,6,opt,name=logHandler" json:"logHandler,omitempty"`
	// tickHandler相关
	Symbol   string `protobuf:"bytes,7,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,8,opt,name=exchange" json:"exchange,omitempty"`
}

func (m *BfConnectReq) Reset()                    { *m = BfConnectReq{} }
func (m *BfConnectReq) String() string            { return proto.CompactTextString(m) }
func (*BfConnectReq) ProtoMessage()               {}
func (*BfConnectReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

// 获取合约信息传入的对象类
type BfGetContractReq struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 获取全部合约时候可以用index来枚举，从1开始，返回空结束
	Index int32 `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	// 过滤条件，指定是否要求已经订阅
	Subscribled bool `protobuf:"varint,4,opt,name=subscribled" json:"subscribled,omitempty"`
}

func (m *BfGetContractReq) Reset()                    { *m = BfGetContractReq{} }
func (m *BfGetContractReq) String() string            { return proto.CompactTextString(m) }
func (*BfGetContractReq) ProtoMessage()               {}
func (*BfGetContractReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func init() {
	proto.RegisterType((*BfVoid)(nil), "bfgateway.BfVoid")
	proto.RegisterType((*BfTickData)(nil), "bfgateway.BfTickData")
	proto.RegisterType((*BfTradeData)(nil), "bfgateway.BfTradeData")
	proto.RegisterType((*BfOrderData)(nil), "bfgateway.BfOrderData")
	proto.RegisterType((*BfPositionData)(nil), "bfgateway.BfPositionData")
	proto.RegisterType((*BfAccountData)(nil), "bfgateway.BfAccountData")
	proto.RegisterType((*BfErrorData)(nil), "bfgateway.BfErrorData")
	proto.RegisterType((*BfLogData)(nil), "bfgateway.BfLogData")
	proto.RegisterType((*BfContractData)(nil), "bfgateway.BfContractData")
	proto.RegisterType((*BfNotificationData)(nil), "bfgateway.BfNotificationData")
	proto.RegisterType((*BfPingData)(nil), "bfgateway.BfPingData")
	proto.RegisterType((*BfKvData)(nil), "bfgateway.BfKvData")
	proto.RegisterType((*BfSendOrderReq)(nil), "bfgateway.BfSendOrderReq")
	proto.RegisterType((*BfSendOrderResp)(nil), "bfgateway.BfSendOrderResp")
	proto.RegisterType((*BfCancelOrderReq)(nil), "bfgateway.BfCancelOrderReq")
	proto.RegisterType((*BfConnectReq)(nil), "bfgateway.BfConnectReq")
	proto.RegisterType((*BfGetContractReq)(nil), "bfgateway.BfGetContractReq")
	proto.RegisterEnum("bfgateway.BfDirection", BfDirection_name, BfDirection_value)
	proto.RegisterEnum("bfgateway.BfOffset", BfOffset_name, BfOffset_value)
	proto.RegisterEnum("bfgateway.BfStatus", BfStatus_name, BfStatus_value)
	proto.RegisterEnum("bfgateway.BfProduct", BfProduct_name, BfProduct_value)
	proto.RegisterEnum("bfgateway.BfPriceType", BfPriceType_name, BfPriceType_value)
	proto.RegisterEnum("bfgateway.BfNoticationType", BfNoticationType_name, BfNoticationType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for BfGatewayService service

type BfGatewayServiceClient interface {
	// 请求push
	Connect(ctx context.Context, in *BfConnectReq, opts ...grpc.CallOption) (BfGatewayService_ConnectClient, error)
	// 断开push
	Disconnect(ctx context.Context, in *BfVoid, opts ...grpc.CallOption) (*BfVoid, error)
	// 活跃检测
	Ping(ctx context.Context, in *BfPingData, opts ...grpc.CallOption) (*BfPingData, error)
	// 获取交易合约信息
	GetContract(ctx context.Context, in *BfGetContractReq, opts ...grpc.CallOption) (*BfContractData, error)
	// 发单
	SendOrder(ctx context.Context, in *BfSendOrderReq, opts ...grpc.CallOption) (*BfSendOrderResp, error)
	// 撤单
	CancelOrder(ctx context.Context, in *BfCancelOrderReq, opts ...grpc.CallOption) (*BfVoid, error)
	// 查询账户信息
	QueryAccount(ctx context.Context, in *BfVoid, opts ...grpc.CallOption) (*BfVoid, error)
	// 查询持仓信息
	QueryPosition(ctx context.Context, in *BfVoid, opts ...grpc.CallOption) (*BfVoid, error)
}

type bfGatewayServiceClient struct {
	cc *grpc.ClientConn
}

func NewBfGatewayServiceClient(cc *grpc.ClientConn) BfGatewayServiceClient {
	return &bfGatewayServiceClient{cc}
}

func (c *bfGatewayServiceClient) Connect(ctx context.Context, in *BfConnectReq, opts ...grpc.CallOption) (BfGatewayService_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfGatewayService_serviceDesc.Streams[0], c.cc, "/bfgateway.BfGatewayService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfGatewayServiceConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfGatewayService_ConnectClient interface {
	Recv() (*google_protobuf.Any, error)
	grpc.ClientStream
}

type bfGatewayServiceConnectClient struct {
	grpc.ClientStream
}

func (x *bfGatewayServiceConnectClient) Recv() (*google_protobuf.Any, error) {
	m := new(google_protobuf.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfGatewayServiceClient) Disconnect(ctx context.Context, in *BfVoid, opts ...grpc.CallOption) (*BfVoid, error) {
	out := new(BfVoid)
	err := grpc.Invoke(ctx, "/bfgateway.BfGatewayService/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) Ping(ctx context.Context, in *BfPingData, opts ...grpc.CallOption) (*BfPingData, error) {
	out := new(BfPingData)
	err := grpc.Invoke(ctx, "/bfgateway.BfGatewayService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) GetContract(ctx context.Context, in *BfGetContractReq, opts ...grpc.CallOption) (*BfContractData, error) {
	out := new(BfContractData)
	err := grpc.Invoke(ctx, "/bfgateway.BfGatewayService/GetContract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) SendOrder(ctx context.Context, in *BfSendOrderReq, opts ...grpc.CallOption) (*BfSendOrderResp, error) {
	out := new(BfSendOrderResp)
	err := grpc.Invoke(ctx, "/bfgateway.BfGatewayService/SendOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) CancelOrder(ctx context.Context, in *BfCancelOrderReq, opts ...grpc.CallOption) (*BfVoid, error) {
	out := new(BfVoid)
	err := grpc.Invoke(ctx, "/bfgateway.BfGatewayService/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) QueryAccount(ctx context.Context, in *BfVoid, opts ...grpc.CallOption) (*BfVoid, error) {
	out := new(BfVoid)
	err := grpc.Invoke(ctx, "/bfgateway.BfGatewayService/QueryAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) QueryPosition(ctx context.Context, in *BfVoid, opts ...grpc.CallOption) (*BfVoid, error) {
	out := new(BfVoid)
	err := grpc.Invoke(ctx, "/bfgateway.BfGatewayService/QueryPosition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BfGatewayService service

type BfGatewayServiceServer interface {
	// 请求push
	Connect(*BfConnectReq, BfGatewayService_ConnectServer) error
	// 断开push
	Disconnect(context.Context, *BfVoid) (*BfVoid, error)
	// 活跃检测
	Ping(context.Context, *BfPingData) (*BfPingData, error)
	// 获取交易合约信息
	GetContract(context.Context, *BfGetContractReq) (*BfContractData, error)
	// 发单
	SendOrder(context.Context, *BfSendOrderReq) (*BfSendOrderResp, error)
	// 撤单
	CancelOrder(context.Context, *BfCancelOrderReq) (*BfVoid, error)
	// 查询账户信息
	QueryAccount(context.Context, *BfVoid) (*BfVoid, error)
	// 查询持仓信息
	QueryPosition(context.Context, *BfVoid) (*BfVoid, error)
}

func RegisterBfGatewayServiceServer(s *grpc.Server, srv BfGatewayServiceServer) {
	s.RegisterService(&_BfGatewayService_serviceDesc, srv)
}

func _BfGatewayService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BfConnectReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfGatewayServiceServer).Connect(m, &bfGatewayServiceConnectServer{stream})
}

type BfGatewayService_ConnectServer interface {
	Send(*google_protobuf.Any) error
	grpc.ServerStream
}

type bfGatewayServiceConnectServer struct {
	grpc.ServerStream
}

func (x *bfGatewayServiceConnectServer) Send(m *google_protobuf.Any) error {
	return x.ServerStream.SendMsg(m)
}

func _BfGatewayService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfGatewayServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfgateway.BfGatewayService/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfGatewayServiceServer).Disconnect(ctx, req.(*BfVoid))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfGatewayService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfPingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfGatewayServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfgateway.BfGatewayService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfGatewayServiceServer).Ping(ctx, req.(*BfPingData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfGatewayService_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfGetContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfGatewayServiceServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfgateway.BfGatewayService/GetContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfGatewayServiceServer).GetContract(ctx, req.(*BfGetContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfGatewayService_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfSendOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfGatewayServiceServer).SendOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfgateway.BfGatewayService/SendOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfGatewayServiceServer).SendOrder(ctx, req.(*BfSendOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfGatewayService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfCancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfGatewayServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfgateway.BfGatewayService/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfGatewayServiceServer).CancelOrder(ctx, req.(*BfCancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfGatewayService_QueryAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfGatewayServiceServer).QueryAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfgateway.BfGatewayService/QueryAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfGatewayServiceServer).QueryAccount(ctx, req.(*BfVoid))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfGatewayService_QueryPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfGatewayServiceServer).QueryPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfgateway.BfGatewayService/QueryPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfGatewayServiceServer).QueryPosition(ctx, req.(*BfVoid))
	}
	return interceptor(ctx, in, info, handler)
}

var _BfGatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bfgateway.BfGatewayService",
	HandlerType: (*BfGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Disconnect",
			Handler:    _BfGatewayService_Disconnect_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BfGatewayService_Ping_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _BfGatewayService_GetContract_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _BfGatewayService_SendOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _BfGatewayService_CancelOrder_Handler,
		},
		{
			MethodName: "QueryAccount",
			Handler:    _BfGatewayService_QueryAccount_Handler,
		},
		{
			MethodName: "QueryPosition",
			Handler:    _BfGatewayService_QueryPosition_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _BfGatewayService_Connect_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 1657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x8e, 0x8e, 0x96, 0xd6, 0x27, 0x99, 0x71, 0xf2, 0xcb, 0xca, 0xdf, 0x36, 0x20, 0x8a, 0xb4,
	0x75, 0x01, 0xab, 0x71, 0x83, 0x1e, 0x80, 0x02, 0x85, 0x0e, 0xb4, 0x23, 0x44, 0x96, 0x14, 0x8a,
	0x4e, 0xe0, 0xde, 0xb4, 0x14, 0xb9, 0x94, 0x09, 0x53, 0xa4, 0x4a, 0x52, 0x3e, 0xf4, 0xa2, 0x2f,
	0xd0, 0xab, 0xa2, 0x8f, 0xd1, 0x9b, 0x3e, 0x45, 0xaf, 0xfa, 0x18, 0x7d, 0x8c, 0x02, 0xed, 0xce,
	0xec, 0xf2, 0xa4, 0xda, 0x69, 0xe2, 0xdc, 0x69, 0xbf, 0x6f, 0x76, 0x76, 0x77, 0xe6, 0x9b, 0x19,
	0x8a, 0x6c, 0x4e, 0xac, 0xa9, 0x1e, 0xd2, 0x0b, 0xfd, 0x6a, 0x6f, 0xee, 0x7b, 0xa1, 0x27, 0x55,
	0x63, 0xa0, 0xb1, 0x33, 0xf5, 0xbc, 0xa9, 0x43, 0x9b, 0x48, 0x4c, 0x16, 0x56, 0x53, 0x77, 0x85,
	0x95, 0x5c, 0x21, 0xe5, 0xb6, 0xf5, 0xc2, 0xb3, 0x4d, 0xf9, 0xb7, 0x22, 0x21, 0x6d, 0x4b, 0xb3,
	0x8d, 0xb3, 0xae, 0x1e, 0xea, 0xd2, 0x7d, 0x52, 0x0e, 0xae, 0x66, 0x13, 0xcf, 0xa9, 0xe7, 0x1e,
	0xe6, 0x3e, 0xac, 0xaa, 0x62, 0x25, 0x35, 0x48, 0x85, 0x5e, 0x1a, 0xa7, 0xba, 0x3b, 0xa5, 0xf5,
	0x3c, 0x32, 0xf1, 0x5a, 0x7a, 0x97, 0x10, 0xdd, 0x08, 0x6d, 0xcf, 0x65, 0x1e, 0x68, 0xbd, 0x80,
	0x6c, 0x0a, 0x81, 0xbd, 0x21, 0xf3, 0xaf, 0xd9, 0x33, 0x5a, 0x2f, 0xf2, 0xbd, 0xd1, 0x5a, 0xfa,
	0x3f, 0xa9, 0x3a, 0x7a, 0x10, 0x8e, 0x7c, 0xdb, 0xa0, 0xf5, 0x12, 0x23, 0x73, 0x6a, 0x02, 0xc0,
	0x6d, 0xce, 0x3d, 0x67, 0xc1, 0xf6, 0x95, 0x19, 0x55, 0x52, 0xc5, 0x4a, 0x92, 0xc9, 0x9a, 0x37,
	0xa7, 0x6e, 0xcf, 0x0d, 0xa9, 0x4f, 0x83, 0xb0, 0xbe, 0x82, 0x1b, 0x33, 0x18, 0xdc, 0x0a, 0x1c,
	0xbd, 0xe0, 0xfb, 0x2b, 0xb8, 0x3f, 0x85, 0xc0, 0xc9, 0x60, 0xcf, 0x4f, 0xae, 0xf2, 0x93, 0x63,
	0x00, 0xd8, 0x53, 0x7b, 0x7a, 0xca, 0x59, 0xc2, 0xd9, 0x18, 0x80, 0x17, 0x39, 0xde, 0x05, 0x27,
	0x57, 0x91, 0x8c, 0xd7, 0xd2, 0xfb, 0x64, 0x7d, 0xee, 0xd3, 0x8e, 0xe3, 0x05, 0x94, 0x1b, 0xac,
	0xa1, 0x41, 0x16, 0x84, 0xdb, 0x2d, 0xe6, 0x73, 0xea, 0xf7, 0xed, 0x99, 0x1d, 0xd6, 0xd7, 0xd1,
	0x24, 0x85, 0xe0, 0xed, 0xbd, 0x8b, 0x88, 0xdf, 0xe0, 0x7c, 0x82, 0xc0, 0xfd, 0x26, 0xb6, 0x89,
	0xbe, 0x1e, 0xd7, 0x37, 0xf9, 0xfd, 0x62, 0x00, 0x58, 0x3d, 0x38, 0x13, 0x6c, 0x8d, 0xb3, 0x31,
	0x00, 0xbe, 0x99, 0x29, 0x0f, 0xc3, 0xe3, 0xfa, 0x16, 0x8f, 0x4c, 0x82, 0x60, 0x3e, 0x83, 0xb3,
	0x88, 0x97, 0x38, 0x9f, 0x20, 0xf2, 0xef, 0x79, 0xb2, 0xca, 0x24, 0xe3, 0xeb, 0x26, 0xbd, 0xb5,
	0x66, 0xea, 0x64, 0x25, 0x04, 0x07, 0x3d, 0x53, 0x08, 0x26, 0x5a, 0xe2, 0xcb, 0xac, 0xa1, 0x6f,
	0x52, 0x9f, 0x71, 0x5c, 0x2e, 0x09, 0x20, 0x3d, 0x21, 0x55, 0xd3, 0xf6, 0x29, 0x8a, 0x0b, 0xf5,
	0xb2, 0xb1, 0x7f, 0x7f, 0x2f, 0xa9, 0x81, 0xb6, 0xd5, 0x8d, 0x58, 0x35, 0x31, 0x94, 0x3e, 0x26,
	0x65, 0xcf, 0xb2, 0x02, 0x1a, 0xa2, 0x8e, 0x36, 0xf6, 0xef, 0x66, 0xb6, 0x0c, 0x91, 0x52, 0x85,
	0x89, 0xb4, 0x4d, 0x4a, 0x73, 0x4c, 0x1c, 0x57, 0x15, 0x5f, 0xa4, 0xa4, 0x58, 0xc9, 0x48, 0x91,
	0x5d, 0x37, 0x14, 0x91, 0xe0, 0x32, 0x62, 0xd7, 0x8d, 0x81, 0x98, 0x45, 0xed, 0x93, 0x14, 0x0b,
	0x80, 0xfc, 0x6b, 0x01, 0x02, 0x89, 0x4f, 0xbb, 0x75, 0x20, 0x33, 0xe1, 0x2a, 0xbc, 0x32, 0x5c,
	0xc5, 0x37, 0x0f, 0x57, 0xe9, 0x0d, 0xc2, 0x55, 0x4e, 0x87, 0xeb, 0x21, 0x59, 0x0d, 0xbd, 0x50,
	0x77, 0x44, 0xf9, 0xad, 0x60, 0xcc, 0xd2, 0x10, 0xd4, 0x30, 0x46, 0xc2, 0xcc, 0x54, 0x68, 0x06,
	0x83, 0x8b, 0x04, 0xa1, 0x1e, 0x2e, 0x02, 0x8c, 0xec, 0xf2, 0x45, 0xc6, 0x48, 0xa9, 0xc2, 0x04,
	0x64, 0x6b, 0xbb, 0x01, 0xf5, 0x43, 0x4c, 0x05, 0x0f, 0x76, 0x0a, 0x49, 0x78, 0x4c, 0xc6, 0x6a,
	0x9a, 0xc7, 0x56, 0xc4, 0x78, 0x43, 0x77, 0x0d, 0xea, 0x20, 0xbf, 0xc6, 0xf9, 0x04, 0x91, 0xff,
	0xcc, 0x91, 0x8d, 0xb6, 0x35, 0xf2, 0x02, 0x5b, 0x74, 0xb6, 0xdb, 0x25, 0x2c, 0x93, 0x92, 0xc2,
	0xeb, 0xa6, 0x84, 0x79, 0x9c, 0x8b, 0x93, 0x31, 0x8f, 0x25, 0x35, 0x5e, 0xc3, 0x2d, 0x2c, 0xdf,
	0xfb, 0x81, 0xf2, 0x82, 0x60, 0xd2, 0xe4, 0xab, 0x1b, 0x32, 0xc3, 0x9e, 0x79, 0x65, 0x46, 0xaf,
	0x10, 0x89, 0x49, 0x21, 0xf2, 0x2f, 0x79, 0xb2, 0xde, 0xb6, 0x5a, 0x86, 0xe1, 0x2d, 0xdc, 0x10,
	0x5f, 0x09, 0xdd, 0x84, 0x2f, 0x99, 0xc4, 0xf8, 0x43, 0x13, 0x00, 0xfc, 0xb1, 0xd6, 0xd6, 0xd6,
	0x1d, 0x88, 0x14, 0xbe, 0x96, 0x75, 0xaa, 0x04, 0x81, 0x4a, 0x9f, 0x08, 0xb2, 0x80, 0x64, 0xb4,
	0x44, 0xbf, 0xe7, 0xba, 0xed, 0xe8, 0x13, 0x87, 0x0f, 0x06, 0xe8, 0x52, 0x11, 0x80, 0xe9, 0xf0,
	0x66, 0x33, 0x3b, 0x08, 0xa2, 0x52, 0x67, 0x7e, 0x13, 0x04, 0xf4, 0xc3, 0xdf, 0x79, 0xa4, 0xfb,
	0x53, 0xdb, 0x15, 0x8f, 0xcc, 0x60, 0xa0, 0x42, 0x83, 0xf7, 0x5c, 0xcf, 0xb2, 0xa3, 0x31, 0x91,
	0x86, 0xa4, 0x47, 0x64, 0x23, 0x8a, 0xa3, 0x30, 0xaa, 0xa0, 0xd1, 0x12, 0x2a, 0x9f, 0x40, 0xa5,
	0x2a, 0xbe, 0xef, 0xf1, 0x4a, 0x95, 0x48, 0xd1, 0xf0, 0x4c, 0x8a, 0xd1, 0x28, 0xa9, 0xf8, 0x1b,
	0x1e, 0x3a, 0xa3, 0x41, 0xa0, 0xc7, 0x39, 0x8f, 0x96, 0xf0, 0x50, 0xf1, 0x53, 0xb9, 0x8c, 0x6a,
	0x34, 0x06, 0xe4, 0x2f, 0x49, 0xb5, 0x6d, 0xf5, 0xbd, 0x69, 0xe4, 0xf8, 0xe2, 0x94, 0x65, 0x92,
	0x87, 0x19, 0x7f, 0xdf, 0xec, 0x58, 0xfe, 0x23, 0x0f, 0x92, 0xec, 0x78, 0x2e, 0xab, 0x1a, 0x23,
	0xbc, 0xb5, 0x24, 0xd9, 0xa1, 0xae, 0x3e, 0x8b, 0x46, 0x37, 0xfe, 0x96, 0xbe, 0x20, 0x6b, 0xec,
	0x53, 0xc1, 0x5c, 0x18, 0x61, 0x87, 0x0d, 0xcd, 0x40, 0x34, 0x8f, 0xed, 0x8c, 0x52, 0x47, 0xdc,
	0x40, 0xcd, 0x58, 0x42, 0x48, 0x79, 0x6f, 0x3c, 0x5a, 0x38, 0xa1, 0x3d, 0x77, 0xa8, 0x90, 0xe5,
	0x12, 0x0a, 0x51, 0x41, 0x45, 0xc2, 0xb7, 0x87, 0xc8, 0x5e, 0x02, 0xc0, 0x7d, 0x67, 0xfa, 0x25,
	0x1f, 0x7f, 0x5c, 0xa4, 0xf1, 0x1a, 0x39, 0xdb, 0xe5, 0x5c, 0x45, 0x70, 0x62, 0x8d, 0xb1, 0xd6,
	0x2f, 0x59, 0xfe, 0xcf, 0x58, 0xfb, 0xaa, 0x22, 0x99, 0x00, 0xc8, 0xda, 0xae, 0x60, 0x89, 0x60,
	0x23, 0x40, 0xfe, 0x39, 0x47, 0xa4, 0xb6, 0x35, 0xf0, 0x42, 0xdb, 0xb2, 0x0d, 0x3d, 0xae, 0xf2,
	0x26, 0x29, 0x86, 0x57, 0x73, 0x9e, 0xec, 0x8d, 0xfd, 0x07, 0x99, 0x10, 0x80, 0x31, 0x37, 0xd5,
	0x98, 0x89, 0x8a, 0x86, 0xb1, 0x3a, 0xf2, 0xd7, 0xab, 0xa3, 0xf0, 0x0a, 0x75, 0x14, 0x97, 0xd5,
	0xf1, 0x08, 0x3e, 0xcf, 0x46, 0xb6, 0xcb, 0xe5, 0x91, 0xf2, 0x92, 0xcb, 0x4a, 0x61, 0x9f, 0x54,
	0xda, 0xd6, 0xb3, 0x73, 0xb4, 0xaa, 0x91, 0xc2, 0x19, 0xbd, 0x12, 0x16, 0xf0, 0x13, 0x5a, 0xc1,
	0xb9, 0xee, 0x2c, 0xa2, 0xd4, 0xf3, 0x85, 0xfc, 0x13, 0xca, 0x67, 0x4c, 0x5d, 0x13, 0xe7, 0x85,
	0x4a, 0xbf, 0xbf, 0x95, 0x7c, 0xe2, 0x3e, 0x53, 0xb8, 0x7e, 0x60, 0x16, 0x33, 0x03, 0xf3, 0x49,
	0x94, 0x76, 0x08, 0xe9, 0x75, 0x13, 0x7c, 0x14, 0xb1, 0x6a, 0x62, 0x98, 0xed, 0x9a, 0xe5, 0x37,
	0x1f, 0x64, 0x2b, 0xff, 0x39, 0xc8, 0xe4, 0x26, 0xd9, 0xcc, 0x04, 0x23, 0x98, 0x67, 0x87, 0x6b,
	0x6e, 0x69, 0xb8, 0xca, 0x26, 0xa9, 0xb1, 0xe2, 0xc3, 0x01, 0xf1, 0x56, 0xf1, 0x7b, 0xe5, 0x08,
	0x97, 0xff, 0xca, 0x91, 0x35, 0xac, 0x71, 0x97, 0x3d, 0x0a, 0x8e, 0x60, 0xae, 0x0c, 0xc7, 0xa6,
	0xa9, 0x6e, 0x1c, 0xaf, 0x81, 0xb3, 0xdd, 0x70, 0xa4, 0xfb, 0xfa, 0x4c, 0xa8, 0x2f, 0x5e, 0x03,
	0x17, 0x84, 0x3e, 0xe7, 0xf8, 0x29, 0xf1, 0x1a, 0xc7, 0x35, 0xab, 0xba, 0xa7, 0xba, 0x6b, 0x3a,
	0xd4, 0xc7, 0x8c, 0x55, 0xd4, 0x34, 0x14, 0x8f, 0xeb, 0xc8, 0xa4, 0x84, 0x26, 0x19, 0x8c, 0x7f,
	0xb4, 0x4e, 0x23, 0x8b, 0x32, 0x5a, 0xa4, 0x90, 0x54, 0x70, 0x56, 0x6e, 0x0c, 0x4e, 0x25, 0x1b,
	0x1c, 0xf9, 0x47, 0x08, 0xf2, 0x21, 0x0d, 0xa3, 0x26, 0xf7, 0x16, 0x22, 0xb5, 0x5d, 0x93, 0xf2,
	0xfe, 0x5b, 0x52, 0xf9, 0x02, 0xde, 0x1d, 0x2c, 0x26, 0x81, 0xe1, 0xdb, 0x6c, 0xe4, 0x98, 0xd1,
	0xbb, 0x53, 0xd0, 0xee, 0x77, 0xd0, 0xf8, 0x63, 0x71, 0x49, 0xf7, 0xc8, 0x56, 0xb7, 0xa7, 0x2a,
	0x1d, 0xad, 0x37, 0x1c, 0x7c, 0x7b, 0x3c, 0x78, 0x36, 0x18, 0xbe, 0x1c, 0xd4, 0xee, 0xb0, 0x8a,
	0xdf, 0x48, 0xe0, 0xfe, 0x70, 0x70, 0x58, 0xcb, 0x49, 0x77, 0xc9, 0x66, 0x82, 0x8d, 0x9f, 0x0e,
	0x55, 0xad, 0x96, 0x97, 0xb6, 0xc8, 0x7a, 0x02, 0x0e, 0x14, 0xad, 0x56, 0xd8, 0x0d, 0xa0, 0x72,
	0xb9, 0x16, 0xc1, 0xcf, 0xf0, 0xe0, 0x60, 0xac, 0x68, 0x29, 0xdf, 0x9b, 0x64, 0x55, 0x60, 0xc3,
	0x91, 0x32, 0x60, 0x8e, 0x6b, 0x64, 0x4d, 0x00, 0x9d, 0xfe, 0x70, 0xac, 0x30, 0xaf, 0xec, 0x56,
	0x69, 0x44, 0x1b, 0x76, 0x5b, 0x27, 0xb5, 0x82, 0xb4, 0x43, 0xee, 0xa5, 0xe1, 0x13, 0x65, 0xac,
	0x29, 0x2a, 0x50, 0xc5, 0xdd, 0x0b, 0x38, 0x94, 0x7f, 0x40, 0xc1, 0xa1, 0x63, 0xad, 0xa5, 0x1d,
	0x8f, 0x53, 0x87, 0x6e, 0x93, 0x9a, 0xc0, 0x06, 0x43, 0x4d, 0x53, 0x5b, 0x5d, 0xa5, 0xcb, 0x4e,
	0x66, 0xe7, 0x08, 0x74, 0xd4, 0x52, 0x23, 0x38, 0x9f, 0x32, 0x6e, 0xf5, 0xfb, 0x02, 0x2d, 0xa4,
	0xd0, 0x4e, 0x6b, 0xd0, 0x51, 0xfa, 0x7d, 0x86, 0x16, 0x77, 0x7b, 0x30, 0xed, 0xc4, 0xe0, 0x80,
	0x10, 0x8d, 0xd4, 0x61, 0xf7, 0xb8, 0xa3, 0x65, 0x63, 0x19, 0x81, 0xca, 0xf3, 0xe3, 0x9e, 0x76,
	0xc2, 0x63, 0x19, 0x61, 0x07, 0xc7, 0xda, 0xb1, 0xaa, 0x8c, 0x6b, 0xf9, 0x5d, 0x9c, 0xc9, 0x71,
	0xb7, 0x80, 0xcb, 0x8d, 0xd4, 0x5e, 0x47, 0xd1, 0x4e, 0x46, 0x0a, 0xb8, 0x1b, 0x0e, 0xd0, 0x5d,
	0x9d, 0x6c, 0x27, 0x70, 0xbf, 0x77, 0xd4, 0xd3, 0x70, 0xc9, 0x9c, 0xb2, 0xf0, 0x24, 0xcc, 0x51,
	0x4b, 0x7d, 0xa6, 0x08, 0x2a, 0xbf, 0xeb, 0x80, 0xea, 0xb2, 0xbd, 0x1d, 0x1c, 0xb1, 0x58, 0xf4,
	0x0e, 0x7a, 0x9d, 0xd6, 0x52, 0xf6, 0xdf, 0x23, 0x0f, 0x32, 0x0c, 0x86, 0xe0, 0x65, 0xaf, 0xdf,
	0x6f, 0x2b, 0x87, 0x3d, 0xc8, 0xd8, 0x3b, 0x64, 0x27, 0x63, 0x70, 0x38, 0xd4, 0x3a, 0xc3, 0x01,
	0x33, 0xeb, 0x68, 0xec, 0x21, 0xfb, 0x7f, 0x17, 0x50, 0xe4, 0xbc, 0x31, 0x8d, 0xa9, 0x7f, 0x0e,
	0xfd, 0xf3, 0x2b, 0xb2, 0x22, 0x8a, 0x5e, 0xfa, 0x5f, 0xa6, 0x6d, 0x25, 0xad, 0xa0, 0xb1, 0xbd,
	0xc7, 0xff, 0xe2, 0xef, 0x45, 0x7f, 0xf1, 0xf7, 0x5a, 0xee, 0x95, 0x7c, 0xe7, 0x93, 0x1c, 0xeb,
	0x97, 0xa4, 0x6b, 0x07, 0x86, 0x70, 0xb0, 0x95, 0x71, 0x00, 0xff, 0xfb, 0x1b, 0xff, 0x86, 0xe4,
	0x3b, 0xd2, 0x67, 0xa4, 0x08, 0xa3, 0x46, 0xba, 0x97, 0x6d, 0xc8, 0x62, 0xfa, 0x34, 0xae, 0x87,
	0xd9, 0xbe, 0x43, 0xb2, 0x9a, 0x2a, 0x51, 0x29, 0x3b, 0x22, 0xb3, 0xc5, 0xdb, 0xd8, 0x59, 0x7e,
	0x4c, 0xfc, 0xed, 0xc2, 0x1c, 0x75, 0x49, 0x35, 0xee, 0xc0, 0x52, 0xd6, 0x32, 0x3d, 0xa6, 0x1a,
	0x8d, 0x9b, 0xa8, 0x60, 0xce, 0xbc, 0x7c, 0x4d, 0x56, 0x53, 0x6d, 0x79, 0xe9, 0x3a, 0xd9, 0x86,
	0x7d, 0x53, 0x1c, 0xd6, 0x9e, 0x2f, 0xa8, 0x7f, 0x25, 0xbe, 0x82, 0x5f, 0x3b, 0x7e, 0x9f, 0x93,
	0x75, 0xdc, 0x17, 0x7d, 0x4c, 0xbf, 0xee, 0xc6, 0xf6, 0x47, 0xdf, 0x7c, 0x30, 0xb5, 0xc3, 0xd3,
	0xc5, 0x64, 0x8f, 0x7d, 0xe1, 0x36, 0x83, 0x85, 0x7b, 0xc1, 0x9a, 0xd6, 0x8c, 0x36, 0x99, 0xa9,
	0xd7, 0xd4, 0xe7, 0x76, 0x33, 0xde, 0x33, 0x29, 0x63, 0xae, 0x3f, 0xfd, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x92, 0x5d, 0x74, 0x51, 0xfa, 0x11, 0x00, 0x00,
}
