// Code generated by protoc-gen-go.
// source: bfcta.proto
// DO NOT EDIT!

/*
Package bftrader is a generated protocol buffer package.

package bftrader.bfcta;

It is generated from these files:
	bfcta.proto

It has these top-level messages:
*/
package bftrader

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bftrader1 "."
import google_protobuf "google/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for BfCtaService service

type BfCtaServiceClient interface {
	// 请求push
	Connect(ctx context.Context, in *bftrader1.BfConnectReq, opts ...grpc.CallOption) (BfCtaService_ConnectClient, error)
	// 断开push
	Disconnect(ctx context.Context, in *bftrader1.BfVoid, opts ...grpc.CallOption) (*bftrader1.BfVoid, error)
	// 活跃检测
	Ping(ctx context.Context, in *bftrader1.BfPingData, opts ...grpc.CallOption) (*bftrader1.BfPingData, error)
	// 获取策略信息，如position，用kv最方便
	GetRobotInfo(ctx context.Context, in *bftrader1.BfKvData, opts ...grpc.CallOption) (*bftrader1.BfKvData, error)
	// 发单
	SendOrder(ctx context.Context, in *bftrader1.BfSendOrderReq, opts ...grpc.CallOption) (*bftrader1.BfSendOrderResp, error)
	// 撤单
	CancelOrder(ctx context.Context, in *bftrader1.BfCancelOrderReq, opts ...grpc.CallOption) (*bftrader1.BfVoid, error)
}

type bfCtaServiceClient struct {
	cc *grpc.ClientConn
}

func NewBfCtaServiceClient(cc *grpc.ClientConn) BfCtaServiceClient {
	return &bfCtaServiceClient{cc}
}

func (c *bfCtaServiceClient) Connect(ctx context.Context, in *bftrader1.BfConnectReq, opts ...grpc.CallOption) (BfCtaService_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfCtaService_serviceDesc.Streams[0], c.cc, "/bftrader.BfCtaService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfCtaServiceConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfCtaService_ConnectClient interface {
	Recv() (*google_protobuf.Any, error)
	grpc.ClientStream
}

type bfCtaServiceConnectClient struct {
	grpc.ClientStream
}

func (x *bfCtaServiceConnectClient) Recv() (*google_protobuf.Any, error) {
	m := new(google_protobuf.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfCtaServiceClient) Disconnect(ctx context.Context, in *bftrader1.BfVoid, opts ...grpc.CallOption) (*bftrader1.BfVoid, error) {
	out := new(bftrader1.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfCtaServiceClient) Ping(ctx context.Context, in *bftrader1.BfPingData, opts ...grpc.CallOption) (*bftrader1.BfPingData, error) {
	out := new(bftrader1.BfPingData)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfCtaServiceClient) GetRobotInfo(ctx context.Context, in *bftrader1.BfKvData, opts ...grpc.CallOption) (*bftrader1.BfKvData, error) {
	out := new(bftrader1.BfKvData)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/GetRobotInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfCtaServiceClient) SendOrder(ctx context.Context, in *bftrader1.BfSendOrderReq, opts ...grpc.CallOption) (*bftrader1.BfSendOrderResp, error) {
	out := new(bftrader1.BfSendOrderResp)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/SendOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfCtaServiceClient) CancelOrder(ctx context.Context, in *bftrader1.BfCancelOrderReq, opts ...grpc.CallOption) (*bftrader1.BfVoid, error) {
	out := new(bftrader1.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BfCtaService service

type BfCtaServiceServer interface {
	// 请求push
	Connect(*bftrader1.BfConnectReq, BfCtaService_ConnectServer) error
	// 断开push
	Disconnect(context.Context, *bftrader1.BfVoid) (*bftrader1.BfVoid, error)
	// 活跃检测
	Ping(context.Context, *bftrader1.BfPingData) (*bftrader1.BfPingData, error)
	// 获取策略信息，如position，用kv最方便
	GetRobotInfo(context.Context, *bftrader1.BfKvData) (*bftrader1.BfKvData, error)
	// 发单
	SendOrder(context.Context, *bftrader1.BfSendOrderReq) (*bftrader1.BfSendOrderResp, error)
	// 撤单
	CancelOrder(context.Context, *bftrader1.BfCancelOrderReq) (*bftrader1.BfVoid, error)
}

func RegisterBfCtaServiceServer(s *grpc.Server, srv BfCtaServiceServer) {
	s.RegisterService(&_BfCtaService_serviceDesc, srv)
}

func _BfCtaService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(bftrader1.BfConnectReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfCtaServiceServer).Connect(m, &bfCtaServiceConnectServer{stream})
}

type BfCtaService_ConnectServer interface {
	Send(*google_protobuf.Any) error
	grpc.ServerStream
}

type bfCtaServiceConnectServer struct {
	grpc.ServerStream
}

func (x *bfCtaServiceConnectServer) Send(m *google_protobuf.Any) error {
	return x.ServerStream.SendMsg(m)
}

func _BfCtaService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).Disconnect(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfCtaService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfPingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfCtaService_GetRobotInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfKvData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).GetRobotInfo(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfCtaService_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfSendOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).SendOrder(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfCtaService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfCancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).CancelOrder(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _BfCtaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bftrader.BfCtaService",
	HandlerType: (*BfCtaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Disconnect",
			Handler:    _BfCtaService_Disconnect_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BfCtaService_Ping_Handler,
		},
		{
			MethodName: "GetRobotInfo",
			Handler:    _BfCtaService_GetRobotInfo_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _BfCtaService_SendOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _BfCtaService_CancelOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _BfCtaService_Connect_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xab, 0x88, 0x7f, 0xb6, 0x05, 0x65, 0x28, 0x62, 0xf7, 0xd8, 0x07, 0xd8, 0x4a, 0xf5,
	0x20, 0x88, 0x07, 0x9b, 0x82, 0x88, 0x07, 0xa5, 0x05, 0xef, 0xb3, 0xc9, 0x6c, 0x08, 0x94, 0x9d,
	0xba, 0x1d, 0x2b, 0x7d, 0x6d, 0x9f, 0xc0, 0x4d, 0xd2, 0x6a, 0xc4, 0x78, 0xdc, 0xdf, 0xf7, 0x7d,
	0x3f, 0xd8, 0x51, 0x5d, 0xeb, 0x52, 0x41, 0xb3, 0x0c, 0x2c, 0x0c, 0xc7, 0xd6, 0x49, 0xc0, 0x8c,
	0x82, 0x3e, 0xb5, 0x2e, 0x47, 0xa1, 0x0f, 0xdc, 0xd4, 0x91, 0x1e, 0xe4, 0xcc, 0xf9, 0x82, 0x46,
	0xd5, 0xcb, 0xbe, 0xbb, 0x11, 0xfa, 0x6d, 0x34, 0xfe, 0xdc, 0x57, 0xbd, 0x89, 0x4b, 0x04, 0xe7,
	0x14, 0xd6, 0x45, 0x4a, 0x70, 0xab, 0x8e, 0x12, 0xf6, 0x9e, 0x52, 0x81, 0x73, 0xb3, 0x53, 0x9a,
	0x58, 0xa9, 0xe1, 0x8c, 0xde, 0x74, 0xdf, 0xd4, 0x3e, 0xb3, 0xf3, 0x99, 0x7b, 0xbf, 0x19, 0x76,
	0x2e, 0xf7, 0x60, 0xac, 0xd4, 0xb4, 0x58, 0xa5, 0xdb, 0xfd, 0x59, 0x73, 0xff, 0xca, 0x45, 0xa6,
	0xff, 0x90, 0x61, 0x07, 0xae, 0xd5, 0xc1, 0x4b, 0xe1, 0x73, 0xe8, 0x37, 0xb3, 0x92, 0x4c, 0x51,
	0x50, 0xb7, 0xd2, 0xb8, 0xba, 0x51, 0xbd, 0x07, 0x92, 0x19, 0x5b, 0x96, 0x47, 0xef, 0x18, 0xa0,
	0xd9, 0x7b, 0x5a, 0x57, 0xdb, 0x16, 0x16, 0x97, 0x13, 0x75, 0x32, 0x27, 0x9f, 0x3d, 0x87, 0xc8,
	0xe1, 0xa2, 0x59, 0xf9, 0xc6, 0xe5, 0x27, 0x07, 0xff, 0x24, 0xab, 0x65, 0x74, 0xdc, 0xa9, 0x6e,
	0x82, 0x3e, 0xa5, 0x45, 0x6d, 0xd1, 0xbf, 0x0e, 0xf5, 0x13, 0x94, 0x9e, 0x96, 0x2f, 0xdb, 0xc3,
	0xea, 0x70, 0x57, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x2f, 0xb7, 0xba, 0xc0, 0x01, 0x00,
	0x00,
}
