// Code generated by protoc-gen-go.
// source: bfcta.proto
// DO NOT EDIT!

/*
Package bftrader is a generated protocol buffer package.

package bftrader.bfcta;

It is generated from these files:
	bfcta.proto

It has these top-level messages:
	BfModelData
	BfRobotData
	BfGatewayData
	BfOrderExData
*/
package bftrader

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bftrader1 "."
import google_protobuf "google/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// 模型实现采用的语言和发布方式
type BfModelLangType int32

const (
	BfModelLangType_MODELLANG_UNKNOWN      BfModelLangType = 0
	BfModelLangType_MODELLANG_PYTHONSCRIPT BfModelLangType = 1
	BfModelLangType_MODELLANG_GOLANGEXE    BfModelLangType = 2
	BfModelLangType_MODELLANG_CPPEXE       BfModelLangType = 3
	BfModelLangType_MODELLANG_CPPDLL       BfModelLangType = 4
)

var BfModelLangType_name = map[int32]string{
	0: "MODELLANG_UNKNOWN",
	1: "MODELLANG_PYTHONSCRIPT",
	2: "MODELLANG_GOLANGEXE",
	3: "MODELLANG_CPPEXE",
	4: "MODELLANG_CPPDLL",
}
var BfModelLangType_value = map[string]int32{
	"MODELLANG_UNKNOWN":      0,
	"MODELLANG_PYTHONSCRIPT": 1,
	"MODELLANG_GOLANGEXE":    2,
	"MODELLANG_CPPEXE":       3,
	"MODELLANG_CPPDLL":       4,
}

func (x BfModelLangType) String() string {
	return proto.EnumName(BfModelLangType_name, int32(x))
}
func (BfModelLangType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 模型信息类
type BfModelData struct {
	ModelId  string          `protobuf:"bytes,1,opt,name=modelId" json:"modelId,omitempty"`
	LangType BfModelLangType `protobuf:"varint,2,opt,name=langType,enum=bftrader.BfModelLangType" json:"langType,omitempty"`
	Path     string          `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
}

func (m *BfModelData) Reset()                    { *m = BfModelData{} }
func (m *BfModelData) String() string            { return proto.CompactTextString(m) }
func (*BfModelData) ProtoMessage()               {}
func (*BfModelData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 机器人信息类
type BfRobotData struct {
	RobotId          string `protobuf:"bytes,1,opt,name=robotId" json:"robotId,omitempty"`
	ModelId          string `protobuf:"bytes,2,opt,name=modelId" json:"modelId,omitempty"`
	GatewayId        string `protobuf:"bytes,3,opt,name=gatewayId" json:"gatewayId,omitempty"`
	SymbolWildcard   string `protobuf:"bytes,4,opt,name=symbolWildcard" json:"symbolWildcard,omitempty"`
	ExchangeWildcard string `protobuf:"bytes,5,opt,name=exchangeWildcard" json:"exchangeWildcard,omitempty"`
}

func (m *BfRobotData) Reset()                    { *m = BfRobotData{} }
func (m *BfRobotData) String() string            { return proto.CompactTextString(m) }
func (*BfRobotData) ProtoMessage()               {}
func (*BfRobotData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 网关信息类
type BfGatewayData struct {
	GatewayId string `protobuf:"bytes,1,opt,name=gatewayId" json:"gatewayId,omitempty"`
	Port      int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Ip        string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
}

func (m *BfGatewayData) Reset()                    { *m = BfGatewayData{} }
func (m *BfGatewayData) String() string            { return proto.CompactTextString(m) }
func (*BfGatewayData) ProtoMessage()               {}
func (*BfGatewayData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 委托<-->机器人映射信息类
type BfOrderExData struct {
	BfOrderId string `protobuf:"bytes,1,opt,name=bfOrderId" json:"bfOrderId,omitempty"`
	RobotId   string `protobuf:"bytes,2,opt,name=robotId" json:"robotId,omitempty"`
}

func (m *BfOrderExData) Reset()                    { *m = BfOrderExData{} }
func (m *BfOrderExData) String() string            { return proto.CompactTextString(m) }
func (*BfOrderExData) ProtoMessage()               {}
func (*BfOrderExData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*BfModelData)(nil), "bftrader.BfModelData")
	proto.RegisterType((*BfRobotData)(nil), "bftrader.BfRobotData")
	proto.RegisterType((*BfGatewayData)(nil), "bftrader.BfGatewayData")
	proto.RegisterType((*BfOrderExData)(nil), "bftrader.BfOrderExData")
	proto.RegisterEnum("bftrader.BfModelLangType", BfModelLangType_name, BfModelLangType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for BfCtaService service

type BfCtaServiceClient interface {
	// 请求push
	Connect(ctx context.Context, in *bftrader1.BfConnectReq, opts ...grpc.CallOption) (BfCtaService_ConnectClient, error)
	// 断开push
	Disconnect(ctx context.Context, in *bftrader1.BfVoid, opts ...grpc.CallOption) (*bftrader1.BfVoid, error)
	// 活跃检测
	Ping(ctx context.Context, in *bftrader1.BfPingData, opts ...grpc.CallOption) (*bftrader1.BfPingData, error)
	// 获取策略信息，如position，用kv最方便
	GetRobotInfo(ctx context.Context, in *bftrader1.BfKvData, opts ...grpc.CallOption) (*bftrader1.BfKvData, error)
	// 发单
	SendOrder(ctx context.Context, in *bftrader1.BfSendOrderReq, opts ...grpc.CallOption) (*bftrader1.BfSendOrderResp, error)
	// 撤单
	CancelOrder(ctx context.Context, in *bftrader1.BfCancelOrderReq, opts ...grpc.CallOption) (*bftrader1.BfVoid, error)
}

type bfCtaServiceClient struct {
	cc *grpc.ClientConn
}

func NewBfCtaServiceClient(cc *grpc.ClientConn) BfCtaServiceClient {
	return &bfCtaServiceClient{cc}
}

func (c *bfCtaServiceClient) Connect(ctx context.Context, in *bftrader1.BfConnectReq, opts ...grpc.CallOption) (BfCtaService_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfCtaService_serviceDesc.Streams[0], c.cc, "/bftrader.BfCtaService/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfCtaServiceConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfCtaService_ConnectClient interface {
	Recv() (*google_protobuf.Any, error)
	grpc.ClientStream
}

type bfCtaServiceConnectClient struct {
	grpc.ClientStream
}

func (x *bfCtaServiceConnectClient) Recv() (*google_protobuf.Any, error) {
	m := new(google_protobuf.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfCtaServiceClient) Disconnect(ctx context.Context, in *bftrader1.BfVoid, opts ...grpc.CallOption) (*bftrader1.BfVoid, error) {
	out := new(bftrader1.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfCtaServiceClient) Ping(ctx context.Context, in *bftrader1.BfPingData, opts ...grpc.CallOption) (*bftrader1.BfPingData, error) {
	out := new(bftrader1.BfPingData)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfCtaServiceClient) GetRobotInfo(ctx context.Context, in *bftrader1.BfKvData, opts ...grpc.CallOption) (*bftrader1.BfKvData, error) {
	out := new(bftrader1.BfKvData)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/GetRobotInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfCtaServiceClient) SendOrder(ctx context.Context, in *bftrader1.BfSendOrderReq, opts ...grpc.CallOption) (*bftrader1.BfSendOrderResp, error) {
	out := new(bftrader1.BfSendOrderResp)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/SendOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfCtaServiceClient) CancelOrder(ctx context.Context, in *bftrader1.BfCancelOrderReq, opts ...grpc.CallOption) (*bftrader1.BfVoid, error) {
	out := new(bftrader1.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.BfCtaService/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BfCtaService service

type BfCtaServiceServer interface {
	// 请求push
	Connect(*bftrader1.BfConnectReq, BfCtaService_ConnectServer) error
	// 断开push
	Disconnect(context.Context, *bftrader1.BfVoid) (*bftrader1.BfVoid, error)
	// 活跃检测
	Ping(context.Context, *bftrader1.BfPingData) (*bftrader1.BfPingData, error)
	// 获取策略信息，如position，用kv最方便
	GetRobotInfo(context.Context, *bftrader1.BfKvData) (*bftrader1.BfKvData, error)
	// 发单
	SendOrder(context.Context, *bftrader1.BfSendOrderReq) (*bftrader1.BfSendOrderResp, error)
	// 撤单
	CancelOrder(context.Context, *bftrader1.BfCancelOrderReq) (*bftrader1.BfVoid, error)
}

func RegisterBfCtaServiceServer(s *grpc.Server, srv BfCtaServiceServer) {
	s.RegisterService(&_BfCtaService_serviceDesc, srv)
}

func _BfCtaService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(bftrader1.BfConnectReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfCtaServiceServer).Connect(m, &bfCtaServiceConnectServer{stream})
}

type BfCtaService_ConnectServer interface {
	Send(*google_protobuf.Any) error
	grpc.ServerStream
}

type bfCtaServiceConnectServer struct {
	grpc.ServerStream
}

func (x *bfCtaServiceConnectServer) Send(m *google_protobuf.Any) error {
	return x.ServerStream.SendMsg(m)
}

func _BfCtaService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).Disconnect(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfCtaService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfPingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfCtaService_GetRobotInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfKvData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).GetRobotInfo(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfCtaService_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfSendOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).SendOrder(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfCtaService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfCancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfCtaServiceServer).CancelOrder(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _BfCtaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bftrader.BfCtaService",
	HandlerType: (*BfCtaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Disconnect",
			Handler:    _BfCtaService_Disconnect_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BfCtaService_Ping_Handler,
		},
		{
			MethodName: "GetRobotInfo",
			Handler:    _BfCtaService_GetRobotInfo_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _BfCtaService_SendOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _BfCtaService_CancelOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _BfCtaService_Connect_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xdd, 0x94, 0x36, 0x93, 0x92, 0x9a, 0x21, 0x14, 0xc7, 0xe2, 0x80, 0x7c, 0x40, 0xa8,
	0x07, 0x17, 0x05, 0x90, 0x90, 0x10, 0x87, 0xe6, 0x47, 0x21, 0x6a, 0x9a, 0x04, 0x27, 0x50, 0x38,
	0xa1, 0xb5, 0xbd, 0x4e, 0x2d, 0xb9, 0xde, 0xe0, 0x2c, 0xa5, 0x79, 0x04, 0x9e, 0x87, 0x37, 0xe3,
	0x09, 0xf0, 0xae, 0x9d, 0xd8, 0xf9, 0xe1, 0xe4, 0x9d, 0xef, 0x9b, 0xf9, 0xe6, 0x9b, 0xf1, 0x40,
	0xc5, 0xf1, 0x5d, 0x4e, 0xac, 0x59, 0xcc, 0x38, 0xc3, 0x23, 0xc7, 0xe7, 0x31, 0xf1, 0x68, 0x6c,
	0x9c, 0x38, 0xfe, 0x94, 0x70, 0xfa, 0x8b, 0x2c, 0x52, 0xca, 0xa8, 0x4f, 0x19, 0x9b, 0x86, 0xf4,
	0x5c, 0x46, 0xce, 0x4f, 0xff, 0x9c, 0x44, 0x19, 0x65, 0xc6, 0x50, 0x69, 0xfa, 0x57, 0xcc, 0xa3,
	0x61, 0x9b, 0x70, 0x82, 0x3a, 0x1c, 0xde, 0x8a, 0xa0, 0xe7, 0xe9, 0xca, 0x73, 0xe5, 0x65, 0xd9,
	0x5e, 0x86, 0xf8, 0x16, 0x8e, 0x42, 0x12, 0x4d, 0x27, 0x8b, 0x19, 0xd5, 0xd5, 0x84, 0xaa, 0x36,
	0xea, 0xd6, 0xb2, 0xa3, 0x95, 0x49, 0xf4, 0xb3, 0x04, 0x7b, 0x95, 0x8a, 0x08, 0xa5, 0x19, 0xe1,
	0x37, 0xfa, 0xbe, 0x54, 0x93, 0x6f, 0xf3, 0x8f, 0x22, 0x9a, 0xda, 0xcc, 0x61, 0x7c, 0xd9, 0x34,
	0x16, 0x41, 0xde, 0x34, 0x0b, 0x8b, 0x76, 0xd4, 0x75, 0x3b, 0xcf, 0xa0, 0x9c, 0xcd, 0x98, 0x70,
	0xa9, 0x78, 0x0e, 0xe0, 0x0b, 0xa8, 0xce, 0x17, 0xb7, 0x0e, 0x0b, 0xaf, 0x83, 0xd0, 0x73, 0x49,
	0xec, 0xe9, 0x25, 0x99, 0xb2, 0x81, 0xe2, 0x19, 0x68, 0xf4, 0xde, 0xbd, 0x49, 0xcc, 0xd2, 0x55,
	0xe6, 0x81, 0xcc, 0xdc, 0xc2, 0xcd, 0x4f, 0xf0, 0xb0, 0xe9, 0x77, 0xd3, 0x16, 0xd2, 0xf6, 0x9a,
	0x05, 0x65, 0xd3, 0x82, 0x18, 0x9c, 0xc5, 0x5c, 0xfa, 0x3e, 0xb0, 0xe5, 0x1b, 0xab, 0xa0, 0x06,
	0xb3, 0xcc, 0x6d, 0xf2, 0x32, 0xbb, 0x42, 0x72, 0x18, 0x27, 0x1b, 0xec, 0xdc, 0x2f, 0x25, 0x9d,
	0x14, 0xc8, 0x25, 0x57, 0x40, 0x71, 0x4f, 0xea, 0xda, 0x9e, 0xce, 0x7e, 0x2b, 0x70, 0xb2, 0xf1,
	0x0f, 0xf0, 0x09, 0x3c, 0xba, 0x1a, 0xb6, 0x3b, 0xfd, 0xfe, 0xc5, 0xa0, 0xfb, 0xfd, 0xf3, 0xe0,
	0x72, 0x30, 0xbc, 0x1e, 0x68, 0x7b, 0x68, 0xc0, 0x69, 0x0e, 0x8f, 0xbe, 0x4d, 0x3e, 0x0e, 0x07,
	0xe3, 0x96, 0xdd, 0x1b, 0x4d, 0x34, 0x05, 0x9f, 0xc2, 0xe3, 0x9c, 0xeb, 0x0e, 0xc5, 0xa7, 0xf3,
	0xb5, 0xa3, 0xa9, 0x58, 0x03, 0x2d, 0x27, 0x5a, 0xa3, 0x91, 0x40, 0xf7, 0xb7, 0xd0, 0x76, 0xbf,
	0xaf, 0x95, 0x1a, 0x7f, 0x55, 0x38, 0x6e, 0xfa, 0x2d, 0x4e, 0xc6, 0x34, 0xbe, 0x0b, 0x5c, 0x8a,
	0xef, 0xe1, 0xb0, 0xc5, 0xa2, 0x88, 0xba, 0x1c, 0x4f, 0x8b, 0x27, 0x93, 0x81, 0x36, 0xfd, 0x61,
	0xd4, 0xac, 0xf4, 0x42, 0xad, 0xe5, 0x85, 0x5a, 0x17, 0xd1, 0xc2, 0xdc, 0x7b, 0xa5, 0x60, 0x03,
	0xa0, 0x1d, 0xcc, 0xdd, 0xac, 0x5e, 0x2b, 0xd6, 0x7f, 0x61, 0x81, 0x67, 0x6c, 0x21, 0xe6, 0x1e,
	0xbe, 0x81, 0xd2, 0x28, 0x88, 0xa6, 0x58, 0x2b, 0x72, 0x02, 0x11, 0x3b, 0x36, 0x76, 0xa2, 0x49,
	0xd5, 0x3b, 0x38, 0xee, 0x52, 0x2e, 0xaf, 0xb2, 0x17, 0xf9, 0x0c, 0xb1, 0x98, 0x77, 0x79, 0x27,
	0x6b, 0x77, 0x60, 0x49, 0x65, 0x13, 0xca, 0x63, 0x1a, 0x79, 0xf2, 0x37, 0xa1, 0x5e, 0x4c, 0x59,
	0xc1, 0x62, 0xc8, 0xfa, 0x7f, 0x98, 0xf9, 0x2c, 0xd1, 0xf8, 0x00, 0x95, 0x16, 0x89, 0x5c, 0x1a,
	0xa6, 0x2a, 0xc6, 0xda, 0xa2, 0x72, 0x42, 0xe8, 0xec, 0x18, 0xd9, 0x79, 0x20, 0x17, 0xf7, 0xfa,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x2e, 0x7e, 0xfd, 0x12, 0x04, 0x00, 0x00,
}
