// Code generated by protoc-gen-go.
// source: bfdatafeed.proto
// DO NOT EDIT!

/*
Package bftrader_bfdatafeed is a generated protocol buffer package.

It is generated from these files:
	bfdatafeed.proto

It has these top-level messages:
*/
package bftrader_bfdatafeed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bftrader "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for BfDatafeedService service

type BfDatafeedServiceClient interface {
	// 保存tick
	InsertTick(ctx context.Context, in *bftrader.BfTickData, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
	// 获取tick
	GetTick(ctx context.Context, in *bftrader.BfGetTickReq, opts ...grpc.CallOption) (BfDatafeedService_GetTickClient, error)
	// 删除tick
	DeleteTick(ctx context.Context, in *bftrader.BfDeleteTickReq, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
	// 保存bar
	InsertBar(ctx context.Context, in *bftrader.BfBarData, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
	// 获取bar
	GetBar(ctx context.Context, in *bftrader.BfGetBarReq, opts ...grpc.CallOption) (BfDatafeedService_GetBarClient, error)
	// 删除bar
	DeleteBar(ctx context.Context, in *bftrader.BfDeleteBarReq, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
	// 保存contract
	InsertContract(ctx context.Context, in *bftrader.BfContractData, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
	// 获取contract
	GetContract(ctx context.Context, in *bftrader.BfDatafeedGetContractReq, opts ...grpc.CallOption) (BfDatafeedService_GetContractClient, error)
	// 删除contract
	DeleteContract(ctx context.Context, in *bftrader.BfDatafeedDeleteContractReq, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
}

type bfDatafeedServiceClient struct {
	cc *grpc.ClientConn
}

func NewBfDatafeedServiceClient(cc *grpc.ClientConn) BfDatafeedServiceClient {
	return &bfDatafeedServiceClient{cc}
}

func (c *bfDatafeedServiceClient) InsertTick(ctx context.Context, in *bftrader.BfTickData, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfdatafeed.BfDatafeedService/InsertTick", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) GetTick(ctx context.Context, in *bftrader.BfGetTickReq, opts ...grpc.CallOption) (BfDatafeedService_GetTickClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfDatafeedService_serviceDesc.Streams[0], c.cc, "/bftrader.bfdatafeed.BfDatafeedService/GetTick", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfDatafeedServiceGetTickClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfDatafeedService_GetTickClient interface {
	Recv() (*bftrader.BfTickData, error)
	grpc.ClientStream
}

type bfDatafeedServiceGetTickClient struct {
	grpc.ClientStream
}

func (x *bfDatafeedServiceGetTickClient) Recv() (*bftrader.BfTickData, error) {
	m := new(bftrader.BfTickData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfDatafeedServiceClient) DeleteTick(ctx context.Context, in *bftrader.BfDeleteTickReq, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfdatafeed.BfDatafeedService/DeleteTick", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) InsertBar(ctx context.Context, in *bftrader.BfBarData, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfdatafeed.BfDatafeedService/InsertBar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) GetBar(ctx context.Context, in *bftrader.BfGetBarReq, opts ...grpc.CallOption) (BfDatafeedService_GetBarClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfDatafeedService_serviceDesc.Streams[1], c.cc, "/bftrader.bfdatafeed.BfDatafeedService/GetBar", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfDatafeedServiceGetBarClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfDatafeedService_GetBarClient interface {
	Recv() (*bftrader.BfBarData, error)
	grpc.ClientStream
}

type bfDatafeedServiceGetBarClient struct {
	grpc.ClientStream
}

func (x *bfDatafeedServiceGetBarClient) Recv() (*bftrader.BfBarData, error) {
	m := new(bftrader.BfBarData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfDatafeedServiceClient) DeleteBar(ctx context.Context, in *bftrader.BfDeleteBarReq, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfdatafeed.BfDatafeedService/DeleteBar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) InsertContract(ctx context.Context, in *bftrader.BfContractData, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfdatafeed.BfDatafeedService/InsertContract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) GetContract(ctx context.Context, in *bftrader.BfDatafeedGetContractReq, opts ...grpc.CallOption) (BfDatafeedService_GetContractClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfDatafeedService_serviceDesc.Streams[2], c.cc, "/bftrader.bfdatafeed.BfDatafeedService/GetContract", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfDatafeedServiceGetContractClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfDatafeedService_GetContractClient interface {
	Recv() (*bftrader.BfContractData, error)
	grpc.ClientStream
}

type bfDatafeedServiceGetContractClient struct {
	grpc.ClientStream
}

func (x *bfDatafeedServiceGetContractClient) Recv() (*bftrader.BfContractData, error) {
	m := new(bftrader.BfContractData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfDatafeedServiceClient) DeleteContract(ctx context.Context, in *bftrader.BfDatafeedDeleteContractReq, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfdatafeed.BfDatafeedService/DeleteContract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BfDatafeedService service

type BfDatafeedServiceServer interface {
	// 保存tick
	InsertTick(context.Context, *bftrader.BfTickData) (*bftrader.BfVoid, error)
	// 获取tick
	GetTick(*bftrader.BfGetTickReq, BfDatafeedService_GetTickServer) error
	// 删除tick
	DeleteTick(context.Context, *bftrader.BfDeleteTickReq) (*bftrader.BfVoid, error)
	// 保存bar
	InsertBar(context.Context, *bftrader.BfBarData) (*bftrader.BfVoid, error)
	// 获取bar
	GetBar(*bftrader.BfGetBarReq, BfDatafeedService_GetBarServer) error
	// 删除bar
	DeleteBar(context.Context, *bftrader.BfDeleteBarReq) (*bftrader.BfVoid, error)
	// 保存contract
	InsertContract(context.Context, *bftrader.BfContractData) (*bftrader.BfVoid, error)
	// 获取contract
	GetContract(*bftrader.BfDatafeedGetContractReq, BfDatafeedService_GetContractServer) error
	// 删除contract
	DeleteContract(context.Context, *bftrader.BfDatafeedDeleteContractReq) (*bftrader.BfVoid, error)
}

func RegisterBfDatafeedServiceServer(s *grpc.Server, srv BfDatafeedServiceServer) {
	s.RegisterService(&_BfDatafeedService_serviceDesc, srv)
}

func _BfDatafeedService_InsertTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfTickData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfDatafeedServiceServer).InsertTick(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfDatafeedService_GetTick_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(bftrader.BfGetTickReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfDatafeedServiceServer).GetTick(m, &bfDatafeedServiceGetTickServer{stream})
}

type BfDatafeedService_GetTickServer interface {
	Send(*bftrader.BfTickData) error
	grpc.ServerStream
}

type bfDatafeedServiceGetTickServer struct {
	grpc.ServerStream
}

func (x *bfDatafeedServiceGetTickServer) Send(m *bftrader.BfTickData) error {
	return x.ServerStream.SendMsg(m)
}

func _BfDatafeedService_DeleteTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfDeleteTickReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfDatafeedServiceServer).DeleteTick(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfDatafeedService_InsertBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfBarData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfDatafeedServiceServer).InsertBar(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfDatafeedService_GetBar_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(bftrader.BfGetBarReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfDatafeedServiceServer).GetBar(m, &bfDatafeedServiceGetBarServer{stream})
}

type BfDatafeedService_GetBarServer interface {
	Send(*bftrader.BfBarData) error
	grpc.ServerStream
}

type bfDatafeedServiceGetBarServer struct {
	grpc.ServerStream
}

func (x *bfDatafeedServiceGetBarServer) Send(m *bftrader.BfBarData) error {
	return x.ServerStream.SendMsg(m)
}

func _BfDatafeedService_DeleteBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfDeleteBarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfDatafeedServiceServer).DeleteBar(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfDatafeedService_InsertContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfContractData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfDatafeedServiceServer).InsertContract(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfDatafeedService_GetContract_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(bftrader.BfDatafeedGetContractReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfDatafeedServiceServer).GetContract(m, &bfDatafeedServiceGetContractServer{stream})
}

type BfDatafeedService_GetContractServer interface {
	Send(*bftrader.BfContractData) error
	grpc.ServerStream
}

type bfDatafeedServiceGetContractServer struct {
	grpc.ServerStream
}

func (x *bfDatafeedServiceGetContractServer) Send(m *bftrader.BfContractData) error {
	return x.ServerStream.SendMsg(m)
}

func _BfDatafeedService_DeleteContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfDatafeedDeleteContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfDatafeedServiceServer).DeleteContract(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _BfDatafeedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bftrader.bfdatafeed.BfDatafeedService",
	HandlerType: (*BfDatafeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertTick",
			Handler:    _BfDatafeedService_InsertTick_Handler,
		},
		{
			MethodName: "DeleteTick",
			Handler:    _BfDatafeedService_DeleteTick_Handler,
		},
		{
			MethodName: "InsertBar",
			Handler:    _BfDatafeedService_InsertBar_Handler,
		},
		{
			MethodName: "DeleteBar",
			Handler:    _BfDatafeedService_DeleteBar_Handler,
		},
		{
			MethodName: "InsertContract",
			Handler:    _BfDatafeedService_InsertContract_Handler,
		},
		{
			MethodName: "DeleteContract",
			Handler:    _BfDatafeedService_DeleteContract_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTick",
			Handler:       _BfDatafeedService_GetTick_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBar",
			Handler:       _BfDatafeedService_GetBar_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetContract",
			Handler:       _BfDatafeedService_GetContract_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xcb, 0x4a, 0xc4, 0x30,
	0x14, 0x86, 0xa7, 0x28, 0x23, 0x73, 0x84, 0x32, 0x66, 0x54, 0xb4, 0xcb, 0x82, 0xdb, 0x22, 0x2a,
	0xa2, 0x08, 0x2e, 0xea, 0x80, 0x88, 0x0b, 0x41, 0xc5, 0x7d, 0xdb, 0x9c, 0x40, 0x51, 0x26, 0x1a,
	0x83, 0x8f, 0xe9, 0xf3, 0xb8, 0x34, 0x37, 0xd3, 0xd4, 0x49, 0xb6, 0xff, 0xf9, 0x2f, 0x5f, 0x68,
	0x61, 0xde, 0x32, 0xda, 0xc8, 0x86, 0x21, 0xd2, 0xea, 0x5d, 0x70, 0xc9, 0xc9, 0xa2, 0x65, 0x52,
	0x34, 0x14, 0x45, 0x35, 0x9c, 0x8a, 0xdc, 0x8b, 0xc6, 0x74, 0xf2, 0xbd, 0x09, 0x3b, 0x35, 0x5b,
	0xba, 0xf3, 0x13, 0x8a, 0xaf, 0xbe, 0x43, 0x72, 0x0e, 0x70, 0xb7, 0xfa, 0x44, 0x21, 0x9f, 0xfb,
	0xee, 0x95, 0xec, 0x56, 0x3e, 0x54, 0x33, 0xad, 0x68, 0x7b, 0x31, 0x0f, 0xd5, 0x17, 0xde, 0xd3,
	0x72, 0x42, 0xae, 0x60, 0xeb, 0x16, 0x6d, 0x68, 0x3f, 0x3c, 0x3b, 0xf1, 0x11, 0x3f, 0x8a, 0x68,
	0x59, 0x39, 0x39, 0xce, 0x54, 0x18, 0x96, 0xf8, 0x86, 0x12, 0x4d, 0xfe, 0x30, 0xf4, 0x0d, 0xba,
	0xae, 0x88, 0x2d, 0x9f, 0xc1, 0xcc, 0x12, 0xd7, 0x8d, 0x20, 0x8b, 0xd0, 0xa0, 0x84, 0x24, 0xef,
	0x05, 0x4c, 0x15, 0x9a, 0x8e, 0xec, 0xfd, 0xc3, 0x55, 0x9a, 0x9e, 0x8a, 0x35, 0x19, 0xd8, 0x4b,
	0x98, 0x59, 0x28, 0x1d, 0x3e, 0x58, 0x67, 0x75, 0xf9, 0xd8, 0xe8, 0x35, 0xe4, 0x16, 0xf5, 0x86,
	0xaf, 0xd4, 0xad, 0x93, 0xe3, 0xfc, 0x9f, 0x9a, 0x84, 0x7e, 0x80, 0x6d, 0x05, 0xe8, 0xc3, 0xe5,
	0x68, 0xdc, 0x7d, 0xc8, 0xc0, 0xa0, 0x31, 0x92, 0x03, 0xe6, 0x2d, 0xf7, 0x90, 0x5b, 0x68, 0xdf,
	0x79, 0x14, 0xeb, 0x1c, 0x7b, 0x12, 0xaf, 0xab, 0x37, 0x7e, 0xb2, 0xac, 0x9d, 0x9a, 0x9f, 0xeb,
	0xf4, 0x37, 0x00, 0x00, 0xff, 0xff, 0x77, 0xf9, 0x34, 0xe1, 0x95, 0x02, 0x00, 0x00,
}
