// Code generated by protoc-gen-go.
// source: bfgateway.proto
// DO NOT EDIT!

/*
Package bftrader_bfgateway is a generated protocol buffer package.

It is generated from these files:
	bfgateway.proto

It has these top-level messages:
*/
package bftrader_bfgateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bftrader "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for BfGatewayService service

type BfGatewayServiceClient interface {
	// 建立连接
	Connect(ctx context.Context, in *bftrader.BfConnectReq, opts ...grpc.CallOption) (*bftrader.BfConnectResp, error)
	// 活跃检测
	Ping(ctx context.Context, in *bftrader.BfPingData, opts ...grpc.CallOption) (*bftrader.BfPingData, error)
	// 获取交易合约信息
	GetContract(ctx context.Context, in *bftrader.BfGetContractReq, opts ...grpc.CallOption) (*bftrader.BfContractData, error)
	// 发单
	SendOrder(ctx context.Context, in *bftrader.BfSendOrderReq, opts ...grpc.CallOption) (*bftrader.BfSendOrderResp, error)
	// 撤单
	CancelOrder(ctx context.Context, in *bftrader.BfCancelOrderReq, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
	// 查询账户信息
	QueryAccount(ctx context.Context, in *bftrader.BfVoid, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
	// 查询持仓信息
	QueryPosition(ctx context.Context, in *bftrader.BfVoid, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
	// 关闭连接
	Close(ctx context.Context, in *bftrader.BfVoid, opts ...grpc.CallOption) (*bftrader.BfVoid, error)
}

type bfGatewayServiceClient struct {
	cc *grpc.ClientConn
}

func NewBfGatewayServiceClient(cc *grpc.ClientConn) BfGatewayServiceClient {
	return &bfGatewayServiceClient{cc}
}

func (c *bfGatewayServiceClient) Connect(ctx context.Context, in *bftrader.BfConnectReq, opts ...grpc.CallOption) (*bftrader.BfConnectResp, error) {
	out := new(bftrader.BfConnectResp)
	err := grpc.Invoke(ctx, "/bftrader.bfgateway.BfGatewayService/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) Ping(ctx context.Context, in *bftrader.BfPingData, opts ...grpc.CallOption) (*bftrader.BfPingData, error) {
	out := new(bftrader.BfPingData)
	err := grpc.Invoke(ctx, "/bftrader.bfgateway.BfGatewayService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) GetContract(ctx context.Context, in *bftrader.BfGetContractReq, opts ...grpc.CallOption) (*bftrader.BfContractData, error) {
	out := new(bftrader.BfContractData)
	err := grpc.Invoke(ctx, "/bftrader.bfgateway.BfGatewayService/GetContract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) SendOrder(ctx context.Context, in *bftrader.BfSendOrderReq, opts ...grpc.CallOption) (*bftrader.BfSendOrderResp, error) {
	out := new(bftrader.BfSendOrderResp)
	err := grpc.Invoke(ctx, "/bftrader.bfgateway.BfGatewayService/SendOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) CancelOrder(ctx context.Context, in *bftrader.BfCancelOrderReq, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfgateway.BfGatewayService/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) QueryAccount(ctx context.Context, in *bftrader.BfVoid, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfgateway.BfGatewayService/QueryAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) QueryPosition(ctx context.Context, in *bftrader.BfVoid, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfgateway.BfGatewayService/QueryPosition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfGatewayServiceClient) Close(ctx context.Context, in *bftrader.BfVoid, opts ...grpc.CallOption) (*bftrader.BfVoid, error) {
	out := new(bftrader.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.bfgateway.BfGatewayService/Close", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BfGatewayService service

type BfGatewayServiceServer interface {
	// 建立连接
	Connect(context.Context, *bftrader.BfConnectReq) (*bftrader.BfConnectResp, error)
	// 活跃检测
	Ping(context.Context, *bftrader.BfPingData) (*bftrader.BfPingData, error)
	// 获取交易合约信息
	GetContract(context.Context, *bftrader.BfGetContractReq) (*bftrader.BfContractData, error)
	// 发单
	SendOrder(context.Context, *bftrader.BfSendOrderReq) (*bftrader.BfSendOrderResp, error)
	// 撤单
	CancelOrder(context.Context, *bftrader.BfCancelOrderReq) (*bftrader.BfVoid, error)
	// 查询账户信息
	QueryAccount(context.Context, *bftrader.BfVoid) (*bftrader.BfVoid, error)
	// 查询持仓信息
	QueryPosition(context.Context, *bftrader.BfVoid) (*bftrader.BfVoid, error)
	// 关闭连接
	Close(context.Context, *bftrader.BfVoid) (*bftrader.BfVoid, error)
}

func RegisterBfGatewayServiceServer(s *grpc.Server, srv BfGatewayServiceServer) {
	s.RegisterService(&_BfGatewayService_serviceDesc, srv)
}

func _BfGatewayService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfGatewayServiceServer).Connect(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfGatewayService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfPingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfGatewayServiceServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfGatewayService_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfGetContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfGatewayServiceServer).GetContract(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfGatewayService_SendOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfSendOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfGatewayServiceServer).SendOrder(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfGatewayService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfCancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfGatewayServiceServer).CancelOrder(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfGatewayService_QueryAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfGatewayServiceServer).QueryAccount(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfGatewayService_QueryPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfGatewayServiceServer).QueryPosition(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfGatewayService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader.BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfGatewayServiceServer).Close(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _BfGatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bftrader.bfgateway.BfGatewayService",
	HandlerType: (*BfGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _BfGatewayService_Connect_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BfGatewayService_Ping_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _BfGatewayService_GetContract_Handler,
		},
		{
			MethodName: "SendOrder",
			Handler:    _BfGatewayService_SendOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _BfGatewayService_CancelOrder_Handler,
		},
		{
			MethodName: "QueryAccount",
			Handler:    _BfGatewayService_QueryAccount_Handler,
		},
		{
			MethodName: "QueryPosition",
			Handler:    _BfGatewayService_QueryPosition_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _BfGatewayService_Close_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0xc9, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xa9, 0xca, 0x22, 0xa6, 0x2c, 0x95, 0x85, 0x58, 0x72, 0xe4, 0x4e, 0x0e, 0x2c, 0x37,
	0x38, 0x90, 0x80, 0x7a, 0xa4, 0x50, 0x89, 0xbb, 0xe3, 0x4c, 0x2a, 0x4b, 0x95, 0xa7, 0x38, 0x53,
	0x50, 0xdf, 0x99, 0x07, 0xe0, 0x88, 0xe3, 0x56, 0x96, 0x0b, 0xa9, 0xd4, 0xeb, 0xff, 0xfd, 0x8b,
	0x47, 0x86, 0xe3, 0xa2, 0x1a, 0x4b, 0xc6, 0x2f, 0x39, 0x4f, 0xa7, 0x96, 0x98, 0x84, 0x28, 0x2a,
	0xb6, 0xb2, 0x44, 0x9b, 0x06, 0x92, 0x1c, 0x05, 0xcd, 0x7b, 0xae, 0xbf, 0xbb, 0xd0, 0xcf, 0xaa,
	0xc1, 0x82, 0x8e, 0xd0, 0x7e, 0x6a, 0x85, 0xe2, 0x1e, 0xf6, 0x72, 0x32, 0x06, 0x15, 0x8b, 0xd3,
	0x34, 0x04, 0xb2, 0x6a, 0x29, 0xbe, 0xe1, 0x47, 0x72, 0xd6, 0xaa, 0xd7, 0xd3, 0xcb, 0x2d, 0x71,
	0x0b, 0xdb, 0x43, 0x6d, 0xc6, 0xe2, 0x24, 0xb6, 0x34, 0xca, 0x93, 0x64, 0x99, 0xb4, 0xaa, 0x2e,
	0xf5, 0x0c, 0xbd, 0x01, 0xb2, 0x6b, 0x72, 0xd0, 0xed, 0x26, 0xb1, 0x2d, 0x02, 0xcd, 0xf6, 0xf9,
	0x9f, 0x6d, 0x0f, 0x96, 0x35, 0x19, 0xec, 0x8f, 0xd0, 0x94, 0x2f, 0xd6, 0x51, 0xb1, 0x62, 0x0c,
	0x72, 0x53, 0x71, 0xb1, 0x86, 0xf8, 0x03, 0x1e, 0xa0, 0x97, 0x4b, 0xa3, 0x70, 0xb2, 0x68, 0x59,
	0x79, 0x4a, 0x04, 0x9a, 0x9e, 0x7e, 0xcc, 0xde, 0x49, 0x97, 0xfe, 0xfe, 0x83, 0xd7, 0x19, 0xda,
	0xf9, 0xa3, 0x52, 0x34, 0x33, 0x2c, 0xfe, 0x79, 0x5a, 0x53, 0x77, 0x70, 0xe8, 0x53, 0x43, 0xaa,
	0x35, 0x6b, 0x32, 0x1b, 0xc6, 0xae, 0x60, 0x27, 0x9f, 0x50, 0x8d, 0x9b, 0xd9, 0xb3, 0xee, 0x4f,
	0xa7, 0x53, 0xec, 0xfa, 0xaf, 0xbf, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x9a, 0x00, 0xa5,
	0x31, 0x02, 0x00, 0x00,
}
