// Code generated by protoc-gen-go.
// source: bfkv.proto
// DO NOT EDIT!

/*
Package bftrader is a generated protocol buffer package.

package bftrader.bfkv;

It is generated from these files:
	bfkv.proto

It has these top-level messages:
*/
package bftrader

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bftrader1 "."
import google_protobuf "google/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for BfKvService service

type BfKvServiceClient interface {
	// 活跃检测
	Ping(ctx context.Context, in *bftrader1.BfPingData, opts ...grpc.CallOption) (*bftrader1.BfPingData, error)
	// stream测试
	PingStreamCS(ctx context.Context, opts ...grpc.CallOption) (BfKvService_PingStreamCSClient, error)
	PingStreamC(ctx context.Context, opts ...grpc.CallOption) (BfKvService_PingStreamCClient, error)
	PingStreamS(ctx context.Context, in *google_protobuf.Any, opts ...grpc.CallOption) (BfKvService_PingStreamSClient, error)
	// Kv服务
	SetKv(ctx context.Context, in *bftrader1.BfKvData, opts ...grpc.CallOption) (*bftrader1.BfVoid, error)
	GetKv(ctx context.Context, in *bftrader1.BfKvData, opts ...grpc.CallOption) (*bftrader1.BfKvData, error)
}

type bfKvServiceClient struct {
	cc *grpc.ClientConn
}

func NewBfKvServiceClient(cc *grpc.ClientConn) BfKvServiceClient {
	return &bfKvServiceClient{cc}
}

func (c *bfKvServiceClient) Ping(ctx context.Context, in *bftrader1.BfPingData, opts ...grpc.CallOption) (*bftrader1.BfPingData, error) {
	out := new(bftrader1.BfPingData)
	err := grpc.Invoke(ctx, "/bftrader.BfKvService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfKvServiceClient) PingStreamCS(ctx context.Context, opts ...grpc.CallOption) (BfKvService_PingStreamCSClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfKvService_serviceDesc.Streams[0], c.cc, "/bftrader.BfKvService/PingStreamCS", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfKvServicePingStreamCSClient{stream}
	return x, nil
}

type BfKvService_PingStreamCSClient interface {
	Send(*google_protobuf.Any) error
	Recv() (*google_protobuf.Any, error)
	grpc.ClientStream
}

type bfKvServicePingStreamCSClient struct {
	grpc.ClientStream
}

func (x *bfKvServicePingStreamCSClient) Send(m *google_protobuf.Any) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bfKvServicePingStreamCSClient) Recv() (*google_protobuf.Any, error) {
	m := new(google_protobuf.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfKvServiceClient) PingStreamC(ctx context.Context, opts ...grpc.CallOption) (BfKvService_PingStreamCClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfKvService_serviceDesc.Streams[1], c.cc, "/bftrader.BfKvService/PingStreamC", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfKvServicePingStreamCClient{stream}
	return x, nil
}

type BfKvService_PingStreamCClient interface {
	Send(*google_protobuf.Any) error
	CloseAndRecv() (*google_protobuf.Any, error)
	grpc.ClientStream
}

type bfKvServicePingStreamCClient struct {
	grpc.ClientStream
}

func (x *bfKvServicePingStreamCClient) Send(m *google_protobuf.Any) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bfKvServicePingStreamCClient) CloseAndRecv() (*google_protobuf.Any, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(google_protobuf.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfKvServiceClient) PingStreamS(ctx context.Context, in *google_protobuf.Any, opts ...grpc.CallOption) (BfKvService_PingStreamSClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfKvService_serviceDesc.Streams[2], c.cc, "/bftrader.BfKvService/PingStreamS", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfKvServicePingStreamSClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfKvService_PingStreamSClient interface {
	Recv() (*google_protobuf.Any, error)
	grpc.ClientStream
}

type bfKvServicePingStreamSClient struct {
	grpc.ClientStream
}

func (x *bfKvServicePingStreamSClient) Recv() (*google_protobuf.Any, error) {
	m := new(google_protobuf.Any)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfKvServiceClient) SetKv(ctx context.Context, in *bftrader1.BfKvData, opts ...grpc.CallOption) (*bftrader1.BfVoid, error) {
	out := new(bftrader1.BfVoid)
	err := grpc.Invoke(ctx, "/bftrader.BfKvService/SetKv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfKvServiceClient) GetKv(ctx context.Context, in *bftrader1.BfKvData, opts ...grpc.CallOption) (*bftrader1.BfKvData, error) {
	out := new(bftrader1.BfKvData)
	err := grpc.Invoke(ctx, "/bftrader.BfKvService/GetKv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BfKvService service

type BfKvServiceServer interface {
	// 活跃检测
	Ping(context.Context, *bftrader1.BfPingData) (*bftrader1.BfPingData, error)
	// stream测试
	PingStreamCS(BfKvService_PingStreamCSServer) error
	PingStreamC(BfKvService_PingStreamCServer) error
	PingStreamS(*google_protobuf.Any, BfKvService_PingStreamSServer) error
	// Kv服务
	SetKv(context.Context, *bftrader1.BfKvData) (*bftrader1.BfVoid, error)
	GetKv(context.Context, *bftrader1.BfKvData) (*bftrader1.BfKvData, error)
}

func RegisterBfKvServiceServer(s *grpc.Server, srv BfKvServiceServer) {
	s.RegisterService(&_BfKvService_serviceDesc, srv)
}

func _BfKvService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfPingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfKvServiceServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfKvService_PingStreamCS_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BfKvServiceServer).PingStreamCS(&bfKvServicePingStreamCSServer{stream})
}

type BfKvService_PingStreamCSServer interface {
	Send(*google_protobuf.Any) error
	Recv() (*google_protobuf.Any, error)
	grpc.ServerStream
}

type bfKvServicePingStreamCSServer struct {
	grpc.ServerStream
}

func (x *bfKvServicePingStreamCSServer) Send(m *google_protobuf.Any) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bfKvServicePingStreamCSServer) Recv() (*google_protobuf.Any, error) {
	m := new(google_protobuf.Any)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BfKvService_PingStreamC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BfKvServiceServer).PingStreamC(&bfKvServicePingStreamCServer{stream})
}

type BfKvService_PingStreamCServer interface {
	SendAndClose(*google_protobuf.Any) error
	Recv() (*google_protobuf.Any, error)
	grpc.ServerStream
}

type bfKvServicePingStreamCServer struct {
	grpc.ServerStream
}

func (x *bfKvServicePingStreamCServer) SendAndClose(m *google_protobuf.Any) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bfKvServicePingStreamCServer) Recv() (*google_protobuf.Any, error) {
	m := new(google_protobuf.Any)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BfKvService_PingStreamS_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf.Any)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfKvServiceServer).PingStreamS(m, &bfKvServicePingStreamSServer{stream})
}

type BfKvService_PingStreamSServer interface {
	Send(*google_protobuf.Any) error
	grpc.ServerStream
}

type bfKvServicePingStreamSServer struct {
	grpc.ServerStream
}

func (x *bfKvServicePingStreamSServer) Send(m *google_protobuf.Any) error {
	return x.ServerStream.SendMsg(m)
}

func _BfKvService_SetKv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfKvData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfKvServiceServer).SetKv(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _BfKvService_GetKv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(bftrader1.BfKvData)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BfKvServiceServer).GetKv(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _BfKvService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bftrader.BfKvService",
	HandlerType: (*BfKvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BfKvService_Ping_Handler,
		},
		{
			MethodName: "SetKv",
			Handler:    _BfKvService_SetKv_Handler,
		},
		{
			MethodName: "GetKv",
			Handler:    _BfKvService_GetKv_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PingStreamCS",
			Handler:       _BfKvService_PingStreamCS_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PingStreamC",
			Handler:       _BfKvService_PingStreamC_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PingStreamS",
			Handler:       _BfKvService_PingStreamS_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0xcb, 0x2e,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x4a, 0x2b, 0x29, 0x4a, 0x4c, 0x49, 0x2d,
	0x92, 0xe2, 0x4f, 0x4a, 0x4b, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0x84, 0x48, 0x49, 0x49, 0xa6,
	0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0x79, 0x49, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x50, 0x29,
	0xa3, 0xe7, 0x4c, 0x5c, 0xdc, 0x4e, 0x69, 0xde, 0x65, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9,
	0x42, 0x26, 0x5c, 0x2c, 0x01, 0x99, 0x79, 0xe9, 0x42, 0x22, 0x7a, 0x30, 0xe3, 0xf4, 0x9c, 0xd2,
	0x40, 0x22, 0x2e, 0x89, 0x25, 0x89, 0x52, 0x58, 0x45, 0x95, 0x18, 0x84, 0x1c, 0xb8, 0x78, 0x40,
	0xbc, 0xe0, 0x92, 0xa2, 0xd4, 0xc4, 0x5c, 0xe7, 0x60, 0xa0, 0x6e, 0x88, 0x8d, 0x7a, 0x30, 0x1b,
	0xf5, 0x1c, 0xf3, 0x2a, 0xa5, 0xb0, 0x8a, 0x2a, 0x31, 0x68, 0x30, 0x1a, 0x30, 0x0a, 0xd9, 0x72,
	0x71, 0x23, 0x99, 0x40, 0xaa, 0x01, 0xa8, 0xda, 0x49, 0xb4, 0x1f, 0x68, 0xbb, 0x3e, 0x17, 0x6b,
	0x70, 0x6a, 0x89, 0x77, 0x99, 0x90, 0x10, 0xb2, 0x07, 0xbd, 0xcb, 0xc0, 0x9e, 0x16, 0x40, 0x16,
	0x0b, 0xcb, 0xcf, 0x4c, 0x01, 0x7a, 0xd8, 0x90, 0x8b, 0xd5, 0x1d, 0xa7, 0x06, 0x2c, 0x62, 0x4a,
	0x0c, 0x49, 0x6c, 0x60, 0x5b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x16, 0x32, 0x87,
	0xb4, 0x01, 0x00, 0x00,
}
