// Code generated by protoc-gen-go.
// source: bftrader.proto
// DO NOT EDIT!

/*
Package bftrader is a generated protocol buffer package.

It is generated from these files:
	bftrader.proto

It has these top-level messages:
	BfVoid
	BfDailyInfo
	BfBidAskInfo
	BfOHLCInfo
	BfTickData
	BfTickPackData
	BfBarData
	BfTradeData
	BfOrderData
	BfPositionData
	BfAccountData
	BfErrorData
	BfLogData
	BfContractData
	BfKvData
	BfSubscribeReq
	BfOrderReq
	BfOrderResponse
	BfCancelOrderReq
	BfConnectReq
	BfGetContractReq
	BfGetTickPackReq
	BfGetBarReq
*/
package bftrader

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// 方向常量
type BfDirection int32

const (
	BfDirection_DIRECTION_UNKNOWN BfDirection = 0
	BfDirection_DIRECTION_NONE    BfDirection = 1
	BfDirection_DIRECTION_LONG    BfDirection = 2
	BfDirection_DIRECTION_SHORT   BfDirection = 3
	BfDirection_DIRECTION_NET     BfDirection = 4
	BfDirection_DIRECTION_SELL    BfDirection = 5
)

var BfDirection_name = map[int32]string{
	0: "DIRECTION_UNKNOWN",
	1: "DIRECTION_NONE",
	2: "DIRECTION_LONG",
	3: "DIRECTION_SHORT",
	4: "DIRECTION_NET",
	5: "DIRECTION_SELL",
}
var BfDirection_value = map[string]int32{
	"DIRECTION_UNKNOWN": 0,
	"DIRECTION_NONE":    1,
	"DIRECTION_LONG":    2,
	"DIRECTION_SHORT":   3,
	"DIRECTION_NET":     4,
	"DIRECTION_SELL":    5,
}

func (x BfDirection) String() string {
	return proto.EnumName(BfDirection_name, int32(x))
}
func (BfDirection) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 开平常量
type BfOffset int32

const (
	BfOffset_OFFSET_UNKNOWN        BfOffset = 0
	BfOffset_OFFSET_NONE           BfOffset = 1
	BfOffset_OFFSET_OPEN           BfOffset = 2
	BfOffset_OFFSET_CLOSE          BfOffset = 3
	BfOffset_OFFSET_CLOSETODAY     BfOffset = 4
	BfOffset_OFFSET_CLOSEYESTERDAY BfOffset = 5
)

var BfOffset_name = map[int32]string{
	0: "OFFSET_UNKNOWN",
	1: "OFFSET_NONE",
	2: "OFFSET_OPEN",
	3: "OFFSET_CLOSE",
	4: "OFFSET_CLOSETODAY",
	5: "OFFSET_CLOSEYESTERDAY",
}
var BfOffset_value = map[string]int32{
	"OFFSET_UNKNOWN":        0,
	"OFFSET_NONE":           1,
	"OFFSET_OPEN":           2,
	"OFFSET_CLOSE":          3,
	"OFFSET_CLOSETODAY":     4,
	"OFFSET_CLOSEYESTERDAY": 5,
}

func (x BfOffset) String() string {
	return proto.EnumName(BfOffset_name, int32(x))
}
func (BfOffset) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 状态常量
type BfStatus int32

const (
	BfStatus_STATUS_UNKNOWN    BfStatus = 0
	BfStatus_STATUS_NOTTRADED  BfStatus = 1
	BfStatus_STATUS_PARTTRADED BfStatus = 2
	BfStatus_STATUS_ALLTRADED  BfStatus = 3
	BfStatus_STATUS_CANCELLED  BfStatus = 4
)

var BfStatus_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "STATUS_NOTTRADED",
	2: "STATUS_PARTTRADED",
	3: "STATUS_ALLTRADED",
	4: "STATUS_CANCELLED",
}
var BfStatus_value = map[string]int32{
	"STATUS_UNKNOWN":    0,
	"STATUS_NOTTRADED":  1,
	"STATUS_PARTTRADED": 2,
	"STATUS_ALLTRADED":  3,
	"STATUS_CANCELLED":  4,
}

func (x BfStatus) String() string {
	return proto.EnumName(BfStatus_name, int32(x))
}
func (BfStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 合约类型常量
type BfProduct int32

const (
	BfProduct_PRODUCT_UNKNOWN     BfProduct = 0
	BfProduct_PRODUCT_NONE        BfProduct = 1
	BfProduct_PRODUCT_EQUITY      BfProduct = 2
	BfProduct_PRODUCT_FUTURES     BfProduct = 3
	BfProduct_PRODUCT_OPTION      BfProduct = 4
	BfProduct_PRODUCT_INDEX       BfProduct = 5
	BfProduct_PRODUCT_COMBINATION BfProduct = 6
	BfProduct_PRODUCT_FOREX       BfProduct = 7
	BfProduct_PRODUCT_SPOT        BfProduct = 8
	BfProduct_PRODUCT_DEFER       BfProduct = 9
)

var BfProduct_name = map[int32]string{
	0: "PRODUCT_UNKNOWN",
	1: "PRODUCT_NONE",
	2: "PRODUCT_EQUITY",
	3: "PRODUCT_FUTURES",
	4: "PRODUCT_OPTION",
	5: "PRODUCT_INDEX",
	6: "PRODUCT_COMBINATION",
	7: "PRODUCT_FOREX",
	8: "PRODUCT_SPOT",
	9: "PRODUCT_DEFER",
}
var BfProduct_value = map[string]int32{
	"PRODUCT_UNKNOWN":     0,
	"PRODUCT_NONE":        1,
	"PRODUCT_EQUITY":      2,
	"PRODUCT_FUTURES":     3,
	"PRODUCT_OPTION":      4,
	"PRODUCT_INDEX":       5,
	"PRODUCT_COMBINATION": 6,
	"PRODUCT_FOREX":       7,
	"PRODUCT_SPOT":        8,
	"PRODUCT_DEFER":       9,
}

func (x BfProduct) String() string {
	return proto.EnumName(BfProduct_name, int32(x))
}
func (BfProduct) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 价格类型常量
type BfPriceType int32

const (
	BfPriceType_PRICETYPE_UNKONWN     BfPriceType = 0
	BfPriceType_PRICETYPE_LIMITPRICE  BfPriceType = 1
	BfPriceType_PRICETYPE_MARKETPRICE BfPriceType = 2
	BfPriceType_PRICETYPE_FAK         BfPriceType = 3
	BfPriceType_PRICETYPE_FOK         BfPriceType = 4
)

var BfPriceType_name = map[int32]string{
	0: "PRICETYPE_UNKONWN",
	1: "PRICETYPE_LIMITPRICE",
	2: "PRICETYPE_MARKETPRICE",
	3: "PRICETYPE_FAK",
	4: "PRICETYPE_FOK",
}
var BfPriceType_value = map[string]int32{
	"PRICETYPE_UNKONWN":     0,
	"PRICETYPE_LIMITPRICE":  1,
	"PRICETYPE_MARKETPRICE": 2,
	"PRICETYPE_FAK":         3,
	"PRICETYPE_FOK":         4,
}

func (x BfPriceType) String() string {
	return proto.EnumName(BfPriceType_name, int32(x))
}
func (BfPriceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 交易所类型
type BfExchange int32

const (
	BfExchange_EXCHANGE_UNKNOWN BfExchange = 0
	BfExchange_EXCHANGE_SSE     BfExchange = 1
	BfExchange_EXCHANGE_SZSE    BfExchange = 2
	BfExchange_EXCHANGE_CFFEX   BfExchange = 3
	BfExchange_EXCHANGE_SHFE    BfExchange = 4
	BfExchange_EXCHANGE_CZCE    BfExchange = 5
	BfExchange_EXCHANGE_DCE     BfExchange = 6
	BfExchange_EXCHANGE_SGE     BfExchange = 7
)

var BfExchange_name = map[int32]string{
	0: "EXCHANGE_UNKNOWN",
	1: "EXCHANGE_SSE",
	2: "EXCHANGE_SZSE",
	3: "EXCHANGE_CFFEX",
	4: "EXCHANGE_SHFE",
	5: "EXCHANGE_CZCE",
	6: "EXCHANGE_DCE",
	7: "EXCHANGE_SGE",
}
var BfExchange_value = map[string]int32{
	"EXCHANGE_UNKNOWN": 0,
	"EXCHANGE_SSE":     1,
	"EXCHANGE_SZSE":    2,
	"EXCHANGE_CFFEX":   3,
	"EXCHANGE_SHFE":    4,
	"EXCHANGE_CZCE":    5,
	"EXCHANGE_DCE":     6,
	"EXCHANGE_SGE":     7,
}

func (x BfExchange) String() string {
	return proto.EnumName(BfExchange_name, int32(x))
}
func (BfExchange) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// Bar周期类型
type BfPeriod int32

const (
	BfPeriod_PERIOD_UNKNOWN BfPeriod = 0
	BfPeriod_PERIOD_M1      BfPeriod = 1
	BfPeriod_PERIOD_D1      BfPeriod = 2
)

var BfPeriod_name = map[int32]string{
	0: "PERIOD_UNKNOWN",
	1: "PERIOD_M1",
	2: "PERIOD_D1",
}
var BfPeriod_value = map[string]int32{
	"PERIOD_UNKNOWN": 0,
	"PERIOD_M1":      1,
	"PERIOD_D1":      2,
}

func (x BfPeriod) String() string {
	return proto.EnumName(BfPeriod_name, int32(x))
}
func (BfPeriod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 空参数
type BfVoid struct {
}

func (m *BfVoid) Reset()                    { *m = BfVoid{} }
func (m *BfVoid) String() string            { return proto.CompactTextString(m) }
func (*BfVoid) ProtoMessage()               {}
func (*BfVoid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// ============================
// 常规行情数据类
type BfDailyInfo struct {
	OpenPrice     float64 `protobuf:"fixed64,1,opt,name=openPrice" json:"openPrice,omitempty"`
	HighPrice     float64 `protobuf:"fixed64,2,opt,name=highPrice" json:"highPrice,omitempty"`
	LowPrice      float64 `protobuf:"fixed64,3,opt,name=lowPrice" json:"lowPrice,omitempty"`
	PreClosePrice float64 `protobuf:"fixed64,4,opt,name=preClosePrice" json:"preClosePrice,omitempty"`
	UpperLimit    float64 `protobuf:"fixed64,5,opt,name=upperLimit" json:"upperLimit,omitempty"`
	LowerLimit    float64 `protobuf:"fixed64,6,opt,name=lowerLimit" json:"lowerLimit,omitempty"`
}

func (m *BfDailyInfo) Reset()                    { *m = BfDailyInfo{} }
func (m *BfDailyInfo) String() string            { return proto.CompactTextString(m) }
func (*BfDailyInfo) ProtoMessage()               {}
func (*BfDailyInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// x档行情
type BfBidAskInfo struct {
	BidPrice  float64 `protobuf:"fixed64,1,opt,name=bidPrice" json:"bidPrice,omitempty"`
	AskPrice  float64 `protobuf:"fixed64,2,opt,name=askPrice" json:"askPrice,omitempty"`
	BidVolume int32   `protobuf:"varint,3,opt,name=bidVolume" json:"bidVolume,omitempty"`
	AskVolume int32   `protobuf:"varint,4,opt,name=askVolume" json:"askVolume,omitempty"`
}

func (m *BfBidAskInfo) Reset()                    { *m = BfBidAskInfo{} }
func (m *BfBidAskInfo) String() string            { return proto.CompactTextString(m) }
func (*BfBidAskInfo) ProtoMessage()               {}
func (*BfBidAskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// OHLC
type BfOHLCInfo struct {
	OpenPrice  float64 `protobuf:"fixed64,1,opt,name=openPrice" json:"openPrice,omitempty"`
	HighPrice  float64 `protobuf:"fixed64,2,opt,name=highPrice" json:"highPrice,omitempty"`
	LowPrice   float64 `protobuf:"fixed64,3,opt,name=lowPrice" json:"lowPrice,omitempty"`
	ClosePrice float64 `protobuf:"fixed64,4,opt,name=closePrice" json:"closePrice,omitempty"`
}

func (m *BfOHLCInfo) Reset()                    { *m = BfOHLCInfo{} }
func (m *BfOHLCInfo) String() string            { return proto.CompactTextString(m) }
func (*BfOHLCInfo) ProtoMessage()               {}
func (*BfOHLCInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Tick行情数据类
type BfTickData struct {
	// 代码相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 成交数据
	Date             string  `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	Time             string  `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	LastPrice        float64 `protobuf:"fixed64,5,opt,name=lastPrice" json:"lastPrice,omitempty"`
	Volume           int32   `protobuf:"varint,6,opt,name=volume" json:"volume,omitempty"`
	OpenInterest     float64 `protobuf:"fixed64,7,opt,name=openInterest" json:"openInterest,omitempty"`
	LastVolume       int32   `protobuf:"varint,8,opt,name=lastVolume" json:"lastVolume,omitempty"`
	LastOpenInterest float64 `protobuf:"fixed64,9,opt,name=lastOpenInterest" json:"lastOpenInterest,omitempty"`
	// x档行情
	BidaskInfo []*BfBidAskInfo `protobuf:"bytes,10,rep,name=bidaskInfo" json:"bidaskInfo,omitempty"`
}

func (m *BfTickData) Reset()                    { *m = BfTickData{} }
func (m *BfTickData) String() string            { return proto.CompactTextString(m) }
func (*BfTickData) ProtoMessage()               {}
func (*BfTickData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BfTickData) GetBidaskInfo() []*BfBidAskInfo {
	if m != nil {
		return m.BidaskInfo
	}
	return nil
}

// 1分钟的tick集合
type BfTickPackData struct {
	// 代码相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	Date     string `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	Time     string `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	// 常规行情
	DailyInfo *BfDailyInfo `protobuf:"bytes,5,opt,name=dailyInfo" json:"dailyInfo,omitempty"`
	// Tick集合
	Ticks []*BfTickData `protobuf:"bytes,6,rep,name=ticks" json:"ticks,omitempty"`
}

func (m *BfTickPackData) Reset()                    { *m = BfTickPackData{} }
func (m *BfTickPackData) String() string            { return proto.CompactTextString(m) }
func (*BfTickPackData) ProtoMessage()               {}
func (*BfTickPackData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BfTickPackData) GetDailyInfo() *BfDailyInfo {
	if m != nil {
		return m.DailyInfo
	}
	return nil
}

func (m *BfTickPackData) GetTicks() []*BfTickData {
	if m != nil {
		return m.Ticks
	}
	return nil
}

// Bar行情数据类
type BfBarData struct {
	// 代码相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 成交数据
	Date             string  `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	Time             string  `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	Volume           int32   `protobuf:"varint,5,opt,name=volume" json:"volume,omitempty"`
	OpenInterest     float64 `protobuf:"fixed64,6,opt,name=openInterest" json:"openInterest,omitempty"`
	LastVolume       int32   `protobuf:"varint,7,opt,name=lastVolume" json:"lastVolume,omitempty"`
	LastOpenInterest float64 `protobuf:"fixed64,8,opt,name=lastOpenInterest" json:"lastOpenInterest,omitempty"`
	// OHLC
	OhlcInfo *BfOHLCInfo `protobuf:"bytes,9,opt,name=ohlcInfo" json:"ohlcInfo,omitempty"`
	// 周期
	Period BfPeriod `protobuf:"varint,10,opt,name=period,enum=bftrader.BfPeriod" json:"period,omitempty"`
	// 常规行情
	DailyInfo *BfDailyInfo `protobuf:"bytes,11,opt,name=dailyInfo" json:"dailyInfo,omitempty"`
}

func (m *BfBarData) Reset()                    { *m = BfBarData{} }
func (m *BfBarData) String() string            { return proto.CompactTextString(m) }
func (*BfBarData) ProtoMessage()               {}
func (*BfBarData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BfBarData) GetOhlcInfo() *BfOHLCInfo {
	if m != nil {
		return m.OhlcInfo
	}
	return nil
}

func (m *BfBarData) GetDailyInfo() *BfDailyInfo {
	if m != nil {
		return m.DailyInfo
	}
	return nil
}

// 成交数据类
type BfTradeData struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	TradeId  string `protobuf:"bytes,3,opt,name=tradeId" json:"tradeId,omitempty"`
	OrderId  string `protobuf:"bytes,4,opt,name=orderId" json:"orderId,omitempty"`
	// 成交相关
	Direction BfDirection `protobuf:"varint,5,opt,name=direction,enum=bftrader.BfDirection" json:"direction,omitempty"`
	Offset    BfOffset    `protobuf:"varint,6,opt,name=offset,enum=bftrader.BfOffset" json:"offset,omitempty"`
	Price     float64     `protobuf:"fixed64,7,opt,name=price" json:"price,omitempty"`
	Volume    int32       `protobuf:"varint,8,opt,name=volume" json:"volume,omitempty"`
	TradeTime string      `protobuf:"bytes,9,opt,name=tradeTime" json:"tradeTime,omitempty"`
}

func (m *BfTradeData) Reset()                    { *m = BfTradeData{} }
func (m *BfTradeData) String() string            { return proto.CompactTextString(m) }
func (*BfTradeData) ProtoMessage()               {}
func (*BfTradeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// 订单数据类
type BfOrderData struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	OrderId  string `protobuf:"bytes,3,opt,name=orderId" json:"orderId,omitempty"`
	// 报单相关
	Direction    BfDirection `protobuf:"varint,4,opt,name=direction,enum=bftrader.BfDirection" json:"direction,omitempty"`
	Offset       BfOffset    `protobuf:"varint,5,opt,name=offset,enum=bftrader.BfOffset" json:"offset,omitempty"`
	Price        float64     `protobuf:"fixed64,6,opt,name=price" json:"price,omitempty"`
	TotalVolume  int32       `protobuf:"varint,7,opt,name=totalVolume" json:"totalVolume,omitempty"`
	TradedVolume int32       `protobuf:"varint,8,opt,name=tradedVolume" json:"tradedVolume,omitempty"`
	Status       BfStatus    `protobuf:"varint,9,opt,name=status,enum=bftrader.BfStatus" json:"status,omitempty"`
	OrderTime    string      `protobuf:"bytes,10,opt,name=orderTime" json:"orderTime,omitempty"`
	CancelTime   string      `protobuf:"bytes,11,opt,name=cancelTime" json:"cancelTime,omitempty"`
}

func (m *BfOrderData) Reset()                    { *m = BfOrderData{} }
func (m *BfOrderData) String() string            { return proto.CompactTextString(m) }
func (*BfOrderData) ProtoMessage()               {}
func (*BfOrderData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// 持仓数据类
type BfPositionData struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 持仓相关
	Direction BfDirection `protobuf:"varint,3,opt,name=direction,enum=bftrader.BfDirection" json:"direction,omitempty"`
	Position  int32       `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
	Frozen    int32       `protobuf:"varint,5,opt,name=frozen" json:"frozen,omitempty"`
	Price     float64     `protobuf:"fixed64,6,opt,name=price" json:"price,omitempty"`
	// 昨持仓
	YdPosition int32 `protobuf:"varint,7,opt,name=ydPosition" json:"ydPosition,omitempty"`
}

func (m *BfPositionData) Reset()                    { *m = BfPositionData{} }
func (m *BfPositionData) String() string            { return proto.CompactTextString(m) }
func (*BfPositionData) ProtoMessage()               {}
func (*BfPositionData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// 账户数据类
type BfAccountData struct {
	// 账号代码相关
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	// 数值相关
	PreBalance     float64 `protobuf:"fixed64,2,opt,name=preBalance" json:"preBalance,omitempty"`
	Balance        float64 `protobuf:"fixed64,3,opt,name=balance" json:"balance,omitempty"`
	Available      float64 `protobuf:"fixed64,4,opt,name=available" json:"available,omitempty"`
	Commission     float64 `protobuf:"fixed64,5,opt,name=commission" json:"commission,omitempty"`
	Margin         float64 `protobuf:"fixed64,6,opt,name=margin" json:"margin,omitempty"`
	CloseProfit    float64 `protobuf:"fixed64,7,opt,name=closeProfit" json:"closeProfit,omitempty"`
	PositionProfit float64 `protobuf:"fixed64,8,opt,name=positionProfit" json:"positionProfit,omitempty"`
}

func (m *BfAccountData) Reset()                    { *m = BfAccountData{} }
func (m *BfAccountData) String() string            { return proto.CompactTextString(m) }
func (*BfAccountData) ProtoMessage()               {}
func (*BfAccountData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// 错误数据类
type BfErrorData struct {
	ErrorId        string `protobuf:"bytes,1,opt,name=errorId" json:"errorId,omitempty"`
	ErrorMsg       string `protobuf:"bytes,2,opt,name=errorMsg" json:"errorMsg,omitempty"`
	AdditionalInfo string `protobuf:"bytes,3,opt,name=additionalInfo" json:"additionalInfo,omitempty"`
}

func (m *BfErrorData) Reset()                    { *m = BfErrorData{} }
func (m *BfErrorData) String() string            { return proto.CompactTextString(m) }
func (*BfErrorData) ProtoMessage()               {}
func (*BfErrorData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

// 日志数据类
type BfLogData struct {
	LogTime    string `protobuf:"bytes,1,opt,name=logTime" json:"logTime,omitempty"`
	LogContent string `protobuf:"bytes,2,opt,name=logContent" json:"logContent,omitempty"`
}

func (m *BfLogData) Reset()                    { *m = BfLogData{} }
func (m *BfLogData) String() string            { return proto.CompactTextString(m) }
func (*BfLogData) ProtoMessage()               {}
func (*BfLogData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// 合约详细信息类
type BfContractData struct {
	// 代码编号相关
	Symbol       string    `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange     string    `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	Name         string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ProductClass BfProduct `protobuf:"varint,4,opt,name=productClass,enum=bftrader.BfProduct" json:"productClass,omitempty"`
	Size         int32     `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	PriceTick    float64   `protobuf:"fixed64,6,opt,name=priceTick" json:"priceTick,omitempty"`
}

func (m *BfContractData) Reset()                    { *m = BfContractData{} }
func (m *BfContractData) String() string            { return proto.CompactTextString(m) }
func (*BfContractData) ProtoMessage()               {}
func (*BfContractData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// K/V数据交换传入传出的数据类
type BfKvData struct {
	// kv对
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *BfKvData) Reset()                    { *m = BfKvData{} }
func (m *BfKvData) String() string            { return proto.CompactTextString(m) }
func (*BfKvData) ProtoMessage()               {}
func (*BfKvData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// 订阅行情时传入的对象类
type BfSubscribeReq struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
}

func (m *BfSubscribeReq) Reset()                    { *m = BfSubscribeReq{} }
func (m *BfSubscribeReq) String() string            { return proto.CompactTextString(m) }
func (*BfSubscribeReq) ProtoMessage()               {}
func (*BfSubscribeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

// 发单时传入的对象类
type BfOrderReq struct {
	// 代码编号相关
	Symbol    string      `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange  string      `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	Price     float64     `protobuf:"fixed64,3,opt,name=price" json:"price,omitempty"`
	Volume    int32       `protobuf:"varint,4,opt,name=volume" json:"volume,omitempty"`
	PriceType BfPriceType `protobuf:"varint,5,opt,name=priceType,enum=bftrader.BfPriceType" json:"priceType,omitempty"`
	Direction BfDirection `protobuf:"varint,6,opt,name=direction,enum=bftrader.BfDirection" json:"direction,omitempty"`
	Offset    BfOffset    `protobuf:"varint,7,opt,name=offset,enum=bftrader.BfOffset" json:"offset,omitempty"`
	Reason    string      `protobuf:"bytes,8,opt,name=reason" json:"reason,omitempty"`
}

func (m *BfOrderReq) Reset()                    { *m = BfOrderReq{} }
func (m *BfOrderReq) String() string            { return proto.CompactTextString(m) }
func (*BfOrderReq) ProtoMessage()               {}
func (*BfOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

// 发单本地返回的对象类
type BfOrderResponse struct {
	OrderId string `protobuf:"bytes,1,opt,name=orderId" json:"orderId,omitempty"`
}

func (m *BfOrderResponse) Reset()                    { *m = BfOrderResponse{} }
func (m *BfOrderResponse) String() string            { return proto.CompactTextString(m) }
func (*BfOrderResponse) ProtoMessage()               {}
func (*BfOrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

// 撤单时传入的对象类
type BfCancelOrderReq struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	OrderId  string `protobuf:"bytes,3,opt,name=orderId" json:"orderId,omitempty"`
	Reason   string `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
}

func (m *BfCancelOrderReq) Reset()                    { *m = BfCancelOrderReq{} }
func (m *BfCancelOrderReq) String() string            { return proto.CompactTextString(m) }
func (*BfCancelOrderReq) ProtoMessage()               {}
func (*BfCancelOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

// 连接时传入的对象类
type BfConnectReq struct {
	// Robot相关
	RobotId  string `protobuf:"bytes,1,opt,name=robotId" json:"robotId,omitempty"`
	Endpoint int32  `protobuf:"varint,2,opt,name=endpoint" json:"endpoint,omitempty"`
	// 回测相关
	FromDay  string `protobuf:"bytes,3,opt,name=fromDay" json:"fromDay,omitempty"`
	FromTime string `protobuf:"bytes,4,opt,name=fromTime" json:"fromTime,omitempty"`
	ToDay    string `protobuf:"bytes,5,opt,name=toDay" json:"toDay,omitempty"`
	ToTime   string `protobuf:"bytes,6,opt,name=toTime" json:"toTime,omitempty"`
}

func (m *BfConnectReq) Reset()                    { *m = BfConnectReq{} }
func (m *BfConnectReq) String() string            { return proto.CompactTextString(m) }
func (*BfConnectReq) ProtoMessage()               {}
func (*BfConnectReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

// 获取合约信息传入的对象类
type BfGetContractReq struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
}

func (m *BfGetContractReq) Reset()                    { *m = BfGetContractReq{} }
func (m *BfGetContractReq) String() string            { return proto.CompactTextString(m) }
func (*BfGetContractReq) ProtoMessage()               {}
func (*BfGetContractReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

// 获取历史Tick数据的对象类（1分钟整存整取）
type BfGetTickPackReq struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	ToDate   string `protobuf:"bytes,3,opt,name=toDate" json:"toDate,omitempty"`
	ToTime   string `protobuf:"bytes,4,opt,name=toTime" json:"toTime,omitempty"`
	Count    int32  `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
}

func (m *BfGetTickPackReq) Reset()                    { *m = BfGetTickPackReq{} }
func (m *BfGetTickPackReq) String() string            { return proto.CompactTextString(m) }
func (*BfGetTickPackReq) ProtoMessage()               {}
func (*BfGetTickPackReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

// 获取历史Bar数据的对象类
type BfGetBarReq struct {
	// 代码编号相关
	Symbol   string   `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string   `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	Period   BfPeriod `protobuf:"varint,3,opt,name=period,enum=bftrader.BfPeriod" json:"period,omitempty"`
	ToDate   string   `protobuf:"bytes,4,opt,name=toDate" json:"toDate,omitempty"`
	ToTime   string   `protobuf:"bytes,5,opt,name=toTime" json:"toTime,omitempty"`
	Count    int32    `protobuf:"varint,6,opt,name=count" json:"count,omitempty"`
}

func (m *BfGetBarReq) Reset()                    { *m = BfGetBarReq{} }
func (m *BfGetBarReq) String() string            { return proto.CompactTextString(m) }
func (*BfGetBarReq) ProtoMessage()               {}
func (*BfGetBarReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func init() {
	proto.RegisterType((*BfVoid)(nil), "bftrader.BfVoid")
	proto.RegisterType((*BfDailyInfo)(nil), "bftrader.BfDailyInfo")
	proto.RegisterType((*BfBidAskInfo)(nil), "bftrader.BfBidAskInfo")
	proto.RegisterType((*BfOHLCInfo)(nil), "bftrader.BfOHLCInfo")
	proto.RegisterType((*BfTickData)(nil), "bftrader.BfTickData")
	proto.RegisterType((*BfTickPackData)(nil), "bftrader.BfTickPackData")
	proto.RegisterType((*BfBarData)(nil), "bftrader.BfBarData")
	proto.RegisterType((*BfTradeData)(nil), "bftrader.BfTradeData")
	proto.RegisterType((*BfOrderData)(nil), "bftrader.BfOrderData")
	proto.RegisterType((*BfPositionData)(nil), "bftrader.BfPositionData")
	proto.RegisterType((*BfAccountData)(nil), "bftrader.BfAccountData")
	proto.RegisterType((*BfErrorData)(nil), "bftrader.BfErrorData")
	proto.RegisterType((*BfLogData)(nil), "bftrader.BfLogData")
	proto.RegisterType((*BfContractData)(nil), "bftrader.BfContractData")
	proto.RegisterType((*BfKvData)(nil), "bftrader.BfKvData")
	proto.RegisterType((*BfSubscribeReq)(nil), "bftrader.BfSubscribeReq")
	proto.RegisterType((*BfOrderReq)(nil), "bftrader.BfOrderReq")
	proto.RegisterType((*BfOrderResponse)(nil), "bftrader.BfOrderResponse")
	proto.RegisterType((*BfCancelOrderReq)(nil), "bftrader.BfCancelOrderReq")
	proto.RegisterType((*BfConnectReq)(nil), "bftrader.BfConnectReq")
	proto.RegisterType((*BfGetContractReq)(nil), "bftrader.BfGetContractReq")
	proto.RegisterType((*BfGetTickPackReq)(nil), "bftrader.BfGetTickPackReq")
	proto.RegisterType((*BfGetBarReq)(nil), "bftrader.BfGetBarReq")
	proto.RegisterEnum("bftrader.BfDirection", BfDirection_name, BfDirection_value)
	proto.RegisterEnum("bftrader.BfOffset", BfOffset_name, BfOffset_value)
	proto.RegisterEnum("bftrader.BfStatus", BfStatus_name, BfStatus_value)
	proto.RegisterEnum("bftrader.BfProduct", BfProduct_name, BfProduct_value)
	proto.RegisterEnum("bftrader.BfPriceType", BfPriceType_name, BfPriceType_value)
	proto.RegisterEnum("bftrader.BfExchange", BfExchange_name, BfExchange_value)
	proto.RegisterEnum("bftrader.BfPeriod", BfPeriod_name, BfPeriod_value)
}

var fileDescriptor0 = []byte{
	// 1687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x58, 0xcd, 0x6e, 0xdb, 0xd6,
	0x12, 0xbe, 0xfa, 0xb5, 0x74, 0xfc, 0x13, 0x86, 0x71, 0x72, 0x7d, 0x2f, 0x2e, 0x2e, 0x02, 0xa2,
	0x28, 0x02, 0x17, 0x08, 0x1a, 0x07, 0x68, 0x37, 0xdd, 0x48, 0x22, 0x65, 0x0b, 0x96, 0x45, 0x95,
	0xa2, 0xd3, 0x38, 0x9b, 0x82, 0x92, 0x28, 0x9b, 0xb0, 0xa4, 0xa3, 0x92, 0xb4, 0x13, 0x67, 0x53,
	0x20, 0x28, 0xd0, 0x2e, 0xfa, 0x08, 0x5d, 0x15, 0x28, 0xd0, 0x7d, 0x1f, 0xa1, 0x40, 0x37, 0x45,
	0x57, 0x7d, 0x84, 0xbe, 0x44, 0x97, 0x9d, 0x39, 0x3f, 0x3c, 0x87, 0x6e, 0x9c, 0x38, 0x0a, 0xd2,
	0x1d, 0xe7, 0x9b, 0xe1, 0x99, 0x99, 0x6f, 0xe6, 0xcc, 0x50, 0x22, 0x1b, 0xc3, 0x49, 0x1a, 0x07,
	0xe3, 0x30, 0xbe, 0xbf, 0x88, 0x69, 0x4a, 0xcd, 0x9a, 0x94, 0xad, 0x1a, 0xa9, 0x36, 0x27, 0x8f,
	0x68, 0x34, 0xb6, 0x7e, 0x2d, 0x90, 0xd5, 0xe6, 0xc4, 0x0e, 0xa2, 0xe9, 0x45, 0x67, 0x3e, 0xa1,
	0xe6, 0xff, 0x48, 0x9d, 0x2e, 0xc2, 0x79, 0x3f, 0x8e, 0x46, 0xe1, 0x56, 0xe1, 0x6e, 0xe1, 0x5e,
	0xc1, 0x53, 0x00, 0x6a, 0x4f, 0xa2, 0xe3, 0x13, 0xae, 0x2d, 0x72, 0x6d, 0x06, 0x98, 0xff, 0x25,
	0xb5, 0x29, 0x7d, 0xca, 0x95, 0x25, 0xa6, 0xcc, 0x64, 0xf3, 0x3d, 0xb2, 0xbe, 0x88, 0xc3, 0xd6,
	0x94, 0x26, 0x21, 0x37, 0x28, 0x33, 0x83, 0x3c, 0x68, 0xfe, 0x9f, 0x90, 0xb3, 0xc5, 0x22, 0x8c,
	0xbb, 0xd1, 0x2c, 0x4a, 0xb7, 0x2a, 0xcc, 0x44, 0x43, 0x50, 0x0f, 0x27, 0x4a, 0x7d, 0x95, 0xeb,
	0x15, 0x62, 0xbd, 0x28, 0x90, 0xb5, 0xe6, 0xa4, 0x19, 0x8d, 0x1b, 0xc9, 0x29, 0x4b, 0x07, 0x42,
	0x1a, 0x46, 0x63, 0x3d, 0x9b, 0x4c, 0x46, 0x5d, 0x90, 0x9c, 0xea, 0xb9, 0x64, 0x32, 0x26, 0x0a,
	0x76, 0x8f, 0xe8, 0xf4, 0x6c, 0xc6, 0x73, 0xa9, 0x78, 0x0a, 0x40, 0x2d, 0x58, 0x0a, 0x6d, 0x99,
	0x6b, 0x33, 0xc0, 0xfa, 0xaa, 0x40, 0x48, 0x73, 0xe2, 0xee, 0x75, 0x5b, 0xef, 0x94, 0x51, 0xe0,
	0x62, 0x74, 0x99, 0x4e, 0x0d, 0xb1, 0x7e, 0x29, 0x62, 0x18, 0x7e, 0x34, 0x3a, 0xb5, 0x83, 0x34,
	0x30, 0xef, 0x90, 0x6a, 0x72, 0x31, 0x1b, 0xd2, 0x29, 0x8b, 0xa1, 0xee, 0x09, 0x09, 0x5d, 0x84,
	0xcf, 0x46, 0x27, 0xc1, 0xfc, 0x98, 0xfb, 0xaf, 0x7b, 0x99, 0x6c, 0x9a, 0xa4, 0x3c, 0x0e, 0x52,
	0xee, 0xba, 0xee, 0xb1, 0x67, 0xc4, 0xd2, 0x48, 0xa4, 0x0d, 0x18, 0x3e, 0x63, 0x12, 0xd3, 0x20,
	0x49, 0x79, 0x24, 0xbc, 0x6a, 0x0a, 0x40, 0xcf, 0xe7, 0x9c, 0xaa, 0x2a, 0xa3, 0x4a, 0x48, 0xa6,
	0x45, 0xd6, 0x90, 0x87, 0xce, 0x3c, 0x0d, 0xe3, 0x30, 0x49, 0xb7, 0x56, 0xd8, 0x8b, 0x39, 0x8c,
	0x15, 0x1c, 0x0e, 0x12, 0x54, 0xd7, 0xd8, 0xfb, 0x1a, 0x62, 0x6e, 0x13, 0x03, 0x25, 0x57, 0x3f,
	0xa7, 0xce, 0xce, 0xf9, 0x1b, 0x6e, 0x7e, 0x44, 0x08, 0x94, 0x30, 0xe0, 0x9d, 0xb1, 0x45, 0xee,
	0x96, 0xee, 0xad, 0xee, 0xdc, 0xb9, 0x9f, 0xdd, 0x11, 0xbd, 0x6f, 0x3c, 0xcd, 0xd2, 0xfa, 0xad,
	0x40, 0x36, 0x38, 0x91, 0xfd, 0xe0, 0x1f, 0x20, 0xf3, 0x21, 0xa9, 0x8f, 0xe5, 0x75, 0x64, 0x64,
	0xae, 0xee, 0xdc, 0xd6, 0xa3, 0xcc, 0xee, 0xaa, 0xa7, 0xec, 0x80, 0x87, 0x4a, 0x0a, 0x01, 0x26,
	0x40, 0x31, 0xa6, 0xb5, 0xa9, 0xbf, 0x20, 0x5b, 0xc0, 0xe3, 0x26, 0xd6, 0x8b, 0x12, 0xa9, 0x43,
	0xb2, 0x41, 0xfc, 0xce, 0x53, 0x51, 0x95, 0xaf, 0xbc, 0xb2, 0xf2, 0xd5, 0xd7, 0x56, 0x7e, 0xe5,
	0x5a, 0x95, 0xaf, 0x5d, 0x51, 0xf9, 0x0f, 0x49, 0x8d, 0x9e, 0x4c, 0x47, 0x8c, 0xd1, 0x3a, 0x63,
	0x34, 0x47, 0x90, 0xbc, 0xaa, 0x5e, 0x66, 0x05, 0xa7, 0x57, 0x61, 0xe8, 0x44, 0x74, 0x0c, 0x7d,
	0x52, 0xb8, 0xb7, 0xb1, 0x63, 0xea, 0xf6, 0x7d, 0xa6, 0xf1, 0x84, 0x45, 0xbe, 0x60, 0xab, 0xd7,
	0x2b, 0x98, 0xf5, 0x7d, 0x11, 0xe7, 0xae, 0x8f, 0x36, 0x4b, 0x97, 0x61, 0x8b, 0xac, 0x30, 0x27,
	0x9d, 0xb1, 0xa8, 0x84, 0x14, 0x51, 0x43, 0x63, 0xf0, 0x0e, 0x1a, 0x5e, 0x0f, 0x29, 0xb2, 0x60,
	0xa3, 0x38, 0x1c, 0xa5, 0x11, 0x9d, 0xb3, 0xaa, 0x6c, 0x5c, 0x0a, 0x56, 0x2a, 0x3d, 0x65, 0x87,
	0x6c, 0xd0, 0xc9, 0x24, 0x09, 0x79, 0xa5, 0x2e, 0xb1, 0xe1, 0x32, 0x8d, 0x27, 0x2c, 0xcc, 0x4d,
	0x52, 0x59, 0xb0, 0x39, 0xc0, 0xaf, 0x33, 0x17, 0xb4, 0x4e, 0xa8, 0xe5, 0x3a, 0x01, 0x26, 0x07,
	0x3b, 0xc8, 0xc7, 0xd6, 0xa9, 0xb3, 0x50, 0x15, 0x80, 0x9d, 0x0a, 0x24, 0xb9, 0x18, 0xfa, 0xdb,
	0x90, 0x24, 0xa9, 0x28, 0xbd, 0x82, 0x8a, 0xf2, 0x1b, 0x53, 0x51, 0xb9, 0x3e, 0x15, 0x55, 0x9d,
	0x8a, 0xbb, 0x64, 0x35, 0xa5, 0x69, 0x30, 0xcd, 0x75, 0xb6, 0x0e, 0xe1, 0xf5, 0x60, 0x47, 0x8e,
	0x73, 0x63, 0x2f, 0x87, 0x61, 0x1c, 0x49, 0x1a, 0xa4, 0x67, 0x09, 0x63, 0xed, 0x52, 0x1c, 0x03,
	0xa6, 0xf1, 0x84, 0x05, 0xdb, 0x40, 0x98, 0x33, 0x23, 0x99, 0x70, 0x92, 0x33, 0x80, 0xed, 0x91,
	0x60, 0x3e, 0x0a, 0xa7, 0x4c, 0xbd, 0xca, 0xd4, 0x1a, 0x62, 0xfd, 0xc1, 0xc6, 0x5f, 0x9f, 0x26,
	0x11, 0x12, 0xb0, 0x74, 0x1d, 0x72, 0x6c, 0x97, 0xae, 0xc9, 0x36, 0x1c, 0xb8, 0x10, 0x8e, 0xc5,
	0x9e, 0xcd, 0x64, 0x0c, 0x62, 0x12, 0xd3, 0xe7, 0xe1, 0x5c, 0x0e, 0x17, 0x2e, 0x5d, 0xc1, 0x3a,
	0x64, 0x79, 0x31, 0x96, 0x49, 0xc8, 0x71, 0xa2, 0x10, 0xeb, 0xeb, 0x22, 0x59, 0x6f, 0x4e, 0x1a,
	0xa3, 0x11, 0x3d, 0x9b, 0xa7, 0x2c, 0x49, 0x5c, 0xf2, 0x5c, 0x84, 0xd6, 0xe1, 0x79, 0x2a, 0x00,
	0xcf, 0x83, 0x4f, 0x97, 0x66, 0x30, 0x45, 0xa2, 0xc4, 0xe2, 0xd6, 0x10, 0x6c, 0xbb, 0xa1, 0x50,
	0xf2, 0xc5, 0x2d, 0x45, 0x76, 0xee, 0x39, 0xcc, 0x81, 0x60, 0x38, 0x95, 0x6b, 0x5b, 0x01, 0xac,
	0x1a, 0x74, 0x36, 0x8b, 0x92, 0x44, 0x5e, 0x50, 0xdc, 0xea, 0x19, 0x82, 0x59, 0xcf, 0x82, 0xf8,
	0x38, 0x9a, 0x8b, 0xf4, 0x84, 0x84, 0x5d, 0x25, 0x76, 0x3f, 0x9d, 0x44, 0x72, 0x97, 0xea, 0x90,
	0xf9, 0x3e, 0xd9, 0x90, 0xdc, 0x09, 0x23, 0x3e, 0x2e, 0x2f, 0xa1, 0xd6, 0x29, 0xde, 0x39, 0x27,
	0x8e, 0x29, 0xbf, 0x73, 0x90, 0x48, 0x88, 0x42, 0x46, 0x82, 0x14, 0x59, 0xb5, 0xf1, 0xf1, 0x20,
	0x39, 0xce, 0xaa, 0x2d, 0x64, 0x74, 0x16, 0x8c, 0xc7, 0xec, 0xd8, 0x60, 0xca, 0x06, 0x23, 0xbf,
	0x7c, 0x97, 0x50, 0xcb, 0xc1, 0x55, 0xd4, 0xa5, 0xc7, 0xd2, 0xd5, 0x94, 0x1e, 0xb3, 0x36, 0x14,
	0xae, 0x84, 0xc8, 0xbf, 0xfb, 0x8e, 0x5b, 0x14, 0x06, 0xfa, 0x3c, 0x15, 0xce, 0x34, 0xc4, 0xfa,
	0x99, 0xf5, 0x28, 0x4a, 0x71, 0x30, 0x4a, 0xdf, 0x66, 0xaf, 0xcd, 0x83, 0x59, 0xb6, 0xd7, 0xf0,
	0xd9, 0xfc, 0x98, 0xac, 0xc1, 0xd7, 0xf3, 0xf8, 0x6c, 0x94, 0xb6, 0x60, 0xaf, 0x24, 0x62, 0x50,
	0xdc, 0xca, 0xed, 0x03, 0xae, 0xf7, 0x72, 0x86, 0x78, 0x58, 0x12, 0x3d, 0x97, 0xab, 0x8f, 0x3d,
	0x63, 0xed, 0x59, 0x3b, 0xe2, 0x4a, 0x16, 0x05, 0x54, 0x80, 0xb5, 0x43, 0x6a, 0xcd, 0xc9, 0xfe,
	0x39, 0x0b, 0xdf, 0x20, 0xa5, 0xd3, 0xf0, 0x42, 0xc4, 0x8e, 0x8f, 0xd8, 0xd7, 0xe7, 0xc1, 0xf4,
	0x4c, 0x46, 0xcd, 0x05, 0xcb, 0xc6, 0xc4, 0x07, 0x67, 0xc3, 0x64, 0x14, 0x47, 0xc3, 0xd0, 0x0b,
	0xbf, 0x58, 0x26, 0x71, 0xeb, 0x3b, 0xf6, 0xad, 0xc8, 0x06, 0xed, 0x92, 0x47, 0xa8, 0x6b, 0x57,
	0x7a, 0xf9, 0xdc, 0x2f, 0xe7, 0xe6, 0xfe, 0x43, 0x49, 0xc4, 0xc5, 0x22, 0x7c, 0xd9, 0x1a, 0xea,
	0x4b, 0xa5, 0xa7, 0xec, 0xf2, 0x23, 0xa4, 0xfa, 0xc6, 0x03, 0x7b, 0xe5, 0xb5, 0x03, 0x1b, 0xa2,
	0x8d, 0xc3, 0x20, 0x81, 0xd3, 0x6b, 0x3c, 0x6f, 0x2e, 0x59, 0x1f, 0x90, 0x1b, 0x19, 0x3b, 0xc9,
	0x82, 0xce, 0x93, 0xdc, 0x5a, 0x29, 0xe4, 0xd6, 0x8a, 0xf5, 0x8c, 0x18, 0xd0, 0x8a, 0x6c, 0x7e,
	0xbe, 0x15, 0xa1, 0x57, 0x2f, 0x2e, 0x15, 0x66, 0x39, 0x17, 0xe6, 0x8f, 0xec, 0xd7, 0x0f, 0xdc,
	0x82, 0x39, 0xe4, 0x8e, 0x6e, 0xe1, 0x88, 0x98, 0x0e, 0xa9, 0x1a, 0x60, 0x52, 0x64, 0x8e, 0xe7,
	0xe3, 0x05, 0x8d, 0xc4, 0x75, 0x82, 0xc1, 0x2a, 0x65, 0x7c, 0x0b, 0x46, 0xe9, 0xcc, 0x0e, 0x2e,
	0xa4, 0x63, 0x21, 0xe2, 0x5b, 0xf8, 0xe8, 0xab, 0xef, 0xbc, 0x4c, 0xc6, 0xfa, 0xa7, 0x14, 0xdf,
	0xa9, 0xf0, 0xf6, 0x64, 0x02, 0x86, 0x9a, 0x52, 0x66, 0x5f, 0xe5, 0xa1, 0x72, 0xc9, 0x6a, 0x23,
	0x49, 0xbb, 0x61, 0x2a, 0xaf, 0xec, 0xb2, 0x8d, 0xfb, 0x6d, 0x41, 0x1c, 0x24, 0x3f, 0xcf, 0x97,
	0x65, 0x9b, 0x05, 0x6a, 0xab, 0x8f, 0x5a, 0x21, 0x69, 0x09, 0x94, 0xf5, 0x04, 0x30, 0x5d, 0xb6,
	0x0a, 0xc4, 0xf5, 0xe6, 0x82, 0xf5, 0x13, 0xfb, 0x35, 0x0d, 0xe1, 0xc0, 0xd7, 0xf5, 0xb2, 0x91,
	0xa8, 0x4f, 0xcf, 0xd2, 0x6b, 0x3f, 0x3d, 0x55, 0xd4, 0xe5, 0x2b, 0xa2, 0xae, 0xbc, 0x3c, 0xea,
	0xaa, 0x16, 0xf5, 0xf6, 0x37, 0xfc, 0x3f, 0x80, 0xec, 0xca, 0xdc, 0x26, 0x37, 0xed, 0x8e, 0xe7,
	0xb4, 0xfc, 0x8e, 0xdb, 0xfb, 0xfc, 0xb0, 0xb7, 0xdf, 0x73, 0x3f, 0xeb, 0x19, 0xff, 0x82, 0x81,
	0xb6, 0xa1, 0xe0, 0x9e, 0xdb, 0x73, 0x8c, 0x42, 0x1e, 0xeb, 0xba, 0xbd, 0x5d, 0xa3, 0x68, 0xde,
	0x22, 0x37, 0x14, 0x36, 0xd8, 0x73, 0x3d, 0xdf, 0x28, 0x99, 0x37, 0xc9, 0xba, 0xf6, 0xb2, 0xe3,
	0x1b, 0xe5, 0xfc, 0xbb, 0x03, 0xa7, 0xdb, 0x35, 0x2a, 0xdb, 0xf0, 0xdb, 0xb9, 0x26, 0xaf, 0x25,
	0x1a, 0xb8, 0xed, 0xf6, 0xc0, 0xf1, 0xb5, 0x20, 0x6e, 0x90, 0x55, 0x81, 0x89, 0x08, 0x14, 0xe0,
	0xf6, 0x9d, 0x1e, 0xb8, 0x37, 0xc8, 0x9a, 0x00, 0x5a, 0x5d, 0x77, 0xe0, 0x80, 0x6f, 0xc8, 0x47,
	0x47, 0x7c, 0xd7, 0x6e, 0x1c, 0x81, 0xff, 0xff, 0x90, 0xdb, 0x3a, 0x7c, 0xe4, 0x0c, 0x7c, 0xc7,
	0x43, 0x55, 0x65, 0xfb, 0x29, 0x46, 0xc1, 0xbf, 0xa2, 0x30, 0x8a, 0x81, 0xdf, 0xf0, 0x0f, 0x07,
	0x5a, 0x14, 0x9b, 0xc4, 0x10, 0x58, 0xcf, 0xf5, 0x7d, 0xaf, 0x61, 0x3b, 0x36, 0x84, 0x02, 0x7e,
	0x04, 0xda, 0x6f, 0x78, 0x12, 0x2e, 0x6a, 0xc6, 0x8d, 0x6e, 0x57, 0xa0, 0x25, 0x0d, 0x6d, 0x35,
	0x7a, 0x2d, 0xc8, 0x1e, 0xd0, 0xf2, 0xf6, 0xef, 0x05, 0x5c, 0x88, 0x62, 0xa1, 0x20, 0x93, 0x7d,
	0xcf, 0xb5, 0x0f, 0x5b, 0x3a, 0x03, 0x90, 0x9f, 0x04, 0x55, 0x11, 0x24, 0xe2, 0x7c, 0x7a, 0xd8,
	0xf1, 0x8f, 0x78, 0x11, 0x24, 0xd6, 0x3e, 0xf4, 0x0f, 0x3d, 0x67, 0x00, 0x3e, 0x35, 0x43, 0xb7,
	0x8f, 0xb4, 0x03, 0x0b, 0x50, 0x18, 0x89, 0x75, 0x7a, 0xb6, 0xf3, 0xd8, 0xa8, 0x98, 0xff, 0x26,
	0xb7, 0x24, 0xd4, 0x72, 0x0f, 0x9a, 0x9d, 0x5e, 0x83, 0xd9, 0x56, 0x75, 0xdb, 0xb6, 0xeb, 0x81,
	0xed, 0x8a, 0x1e, 0xcd, 0xa0, 0xef, 0xfa, 0x46, 0x4d, 0x37, 0xb2, 0x9d, 0xb6, 0xe3, 0x19, 0xf5,
	0xed, 0x2f, 0xb1, 0xbf, 0xb2, 0x91, 0x8e, 0x3c, 0xf5, 0xbd, 0x4e, 0xcb, 0xf1, 0x8f, 0xfa, 0x0e,
	0x26, 0xe6, 0xf6, 0x58, 0x62, 0x5b, 0x64, 0x53, 0xc1, 0xdd, 0xce, 0x41, 0xc7, 0x67, 0x22, 0x24,
	0x08, 0x95, 0x52, 0x9a, 0x83, 0x86, 0xb7, 0xef, 0x08, 0x55, 0x91, 0x7b, 0x93, 0xaa, 0x76, 0x63,
	0x9f, 0xb7, 0x9a, 0x06, 0xb9, 0xfb, 0x40, 0xeb, 0x0f, 0xec, 0x2f, 0x19, 0x47, 0xed, 0x2a, 0xc3,
	0x79, 0xdc, 0xda, 0x6b, 0xf4, 0x76, 0x9d, 0x3c, 0xb1, 0x19, 0x3a, 0x18, 0xa0, 0x5f, 0x38, 0x49,
	0x21, 0x4f, 0x06, 0xe8, 0x0f, 0x28, 0xcc, 0xa0, 0x56, 0xbb, 0x0d, 0x1c, 0x94, 0xf2, 0x66, 0x7b,
	0x6d, 0x87, 0xb3, 0xaa, 0xcc, 0x9e, 0x40, 0xa4, 0x95, 0xdc, 0xf1, 0x36, 0x20, 0xd5, 0xbc, 0xc3,
	0x5d, 0xc7, 0x58, 0xd9, 0xfe, 0x04, 0xfb, 0x8e, 0xdf, 0x71, 0x56, 0x2c, 0xc7, 0xeb, 0xb8, 0xb6,
	0x16, 0xe2, 0x3a, 0xa9, 0x0b, 0xec, 0xe0, 0x01, 0xc4, 0xa7, 0x44, 0xfb, 0x81, 0x51, 0x6c, 0x96,
	0xfe, 0x2c, 0x14, 0x86, 0x55, 0xf6, 0x5f, 0xdf, 0xc3, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0x77, 0x07, 0x99, 0xfd, 0x13, 0x00, 0x00,
}
