// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bfcta.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "bfcta.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bftrader {
namespace bfcta {

namespace {


}  // namespace


void protobuf_AssignDesc_bfcta_2eproto() {
  protobuf_AddDesc_bfcta_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "bfcta.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_bfcta_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_bfcta_2eproto() {
}

void protobuf_AddDesc_bfcta_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::bftrader::protobuf_AddDesc_bftrader_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013bfcta.proto\022\016bftrader.bfcta\032\016bftrader."
    "proto2\363\002\n\014BfCtaService\022<\n\007Connect\022\026.bftr"
    "ader.BfConnectReq\032\027.bftrader.BfConnectRe"
    "sp\"\000\0224\n\004Ping\022\024.bftrader.BfPingData\032\024.bft"
    "rader.BfPingData\"\000\0222\n\nDisconnect\022\020.bftra"
    "der.BfVoid\032\020.bftrader.BfVoid\"\000\0228\n\014GetRob"
    "otInfo\022\022.bftrader.BfKvData\032\022.bftrader.Bf"
    "KvData\"\000\022B\n\tSendOrder\022\030.bftrader.BfSendO"
    "rderReq\032\031.bftrader.BfSendOrderResp\"\000\022=\n\013"
    "CancelOrder\022\032.bftrader.BfCancelOrderReq\032"
    "\020.bftrader.BfVoid\"\000b\006proto3", 427);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "bfcta.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_bfcta_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_bfcta_2eproto {
  StaticDescriptorInitializer_bfcta_2eproto() {
    protobuf_AddDesc_bfcta_2eproto();
  }
} static_descriptor_initializer_bfcta_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace bfcta
}  // namespace bftrader

// @@protoc_insertion_point(global_scope)
