// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bfkv.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "bfkv.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bftrader {
namespace bfkv {

namespace {


}  // namespace


void protobuf_AssignDesc_bfkv_2eproto() {
  protobuf_AddDesc_bfkv_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "bfkv.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_bfkv_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_bfkv_2eproto() {
}

void protobuf_AddDesc_bfkv_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::bftrader::protobuf_AddDesc_bftrader_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nbfkv.proto\022\rbftrader.bfkv\032\016bftrader.pr"
    "oto2q\n\013BfKvService\022/\n\005SetKv\022\022.bftrader.B"
    "fKvData\032\020.bftrader.BfVoid\"\000\0221\n\005GetKv\022\022.b"
    "ftrader.BfKvData\032\022.bftrader.BfKvData\"\000b\006"
    "proto3", 166);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "bfkv.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_bfkv_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_bfkv_2eproto {
  StaticDescriptorInitializer_bfkv_2eproto() {
    protobuf_AddDesc_bfkv_2eproto();
  }
} static_descriptor_initializer_bfkv_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace bfkv
}  // namespace bftrader

// @@protoc_insertion_point(global_scope)
